import assert from'node:assert/strict';import{chromium}from'playwright';import{CASES}from'../../.checks/detectives-game.js';
const browser=await chromium.launch(),base=process.env.E2E_BASE_URL||'http://localhost:3000',out='/Users/jasonchua/Documents/Codex/2026-10-08/read/outputs';
const state=p=>p.evaluate(()=>{const g=window.__detectives().game;return{caseId:g.caseId,place:g.place,who:g.who,found:g.found,deduced:g.deduced,focus:g.focus,pair:g.pair,paused:g.paused,state:g.state,hints:g.hints,mistakes:g.mistakes};});
async function clue(p,c){await p.getByTestId('place-'+c.place).click();await p.getByTestId('spot-'+c.id).click();if(c.kind==='talk'){await p.getByTestId('question').click();}else await p.getByTestId(c.kind==='scent'?'scent':'examine').click();await p.getByTestId('close-dialog').click();assert.ok((await state(p)).found.includes(c.id));}
async function pair(p,d,drag=false){if(drag)await p.getByTestId('clue-'+d.pair[0]).dragTo(p.getByTestId('clue-'+d.pair[1]));else{await p.getByTestId('clue-'+d.pair[0]).click();await p.getByTestId('clue-'+d.pair[1]).click();}assert.deepEqual(new Set((await state(p)).pair),new Set(d.pair));await p.getByTestId('deduce').click();await p.getByTestId('claim-'+d.answer).click();await p.getByTestId('close-dialog').click();assert.ok((await state(p)).deduced.includes(d.id));}
try{
 const p=await browser.newPage({viewport:{width:1536,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(20000);
 await p.goto(base);assert.equal(await p.locator('.arcade-card').count(),30);await p.getByRole('link',{name:/Pawprint Detectives/}).click();await p.getByTestId('start').click();assert.equal(await p.getByTestId('solve').isEnabled(),false);
 await clue(p,CASES[0].clues.find(c=>c.id==='prints'));await clue(p,CASES[0].clues.find(c=>c.id==='baker'));await pair(p,CASES[0].deductions[0],true);await p.getByTestId('spot-baker').click();await p.getByTestId('follow-up').click();assert.match(await p.getByRole('dialog').innerText(),/Milo/);await p.getByTestId('close-dialog').click();
 await p.getByTestId('menu').click();await p.reload();await p.getByTestId('resume').click();assert.ok((await state(p)).paused);assert.equal((await state(p)).deduced.length,1);await p.keyboard.press('Shift+Tab');assert.ok(await p.getByRole('button',{name:'Save & menu',exact:true}).last().evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');assert.equal((await state(p)).paused,false);
 await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>!window.__detectives().stage.motion);const clock=await p.evaluate(()=>window.__detectives().stage.clock);await p.getByTestId('hero-enzo').click();await p.waitForTimeout(120);assert.equal(await p.evaluate(()=>window.__detectives().stage.clock),clock);await p.emulateMedia({reducedMotion:'no-preference'});
 for(let index=0;index<3;index++){const def=CASES[index];let turns=0;while((await state(p)).deduced.length<4&&turns++<6){for(const c of def.clues){const s=await state(p);if(s.found.includes(c.id)||c.need&&!s.found.includes(c.need)&&!s.deduced.includes(c.need))continue;await clue(p,c);}for(const d of def.deductions){const s=await state(p);if(!s.deduced.includes(d.id)&&d.pair.every(id=>s.found.includes(id)))await pair(p,d);}}assert.equal((await state(p)).deduced.length,4);await p.getByTestId('solve').click();assert.equal(await p.getByTestId('submit-case').isEnabled(),false);const muteBefore=await p.getByTestId('sound').getAttribute('aria-label');await p.getByTestId('answer-0').focus();await p.keyboard.press('KeyM');assert.equal(await p.getByTestId('sound').getAttribute('aria-label'),muteBefore,'select typing never toggles game sound');for(let i=0;i<3;i++)await p.getByTestId('answer-'+i).selectOption(String(def.solution[i]));await p.getByTestId('submit-case').click();await p.getByRole('dialog',{name:'Case solved'}).waitFor();assert.ok(await p.getByRole('dialog').getByRole('button').first().evaluate(e=>e===document.activeElement),'result dialog receives focus');assert.equal((await state(p)).state,'closed');assert.equal(await p.evaluate(()=>localStorage.getItem('pawprint-detectives-run-v1')),null);assert.equal(await p.evaluate(i=>JSON.parse(localStorage.getItem('pawprint-detectives-v1')).stars[i],index),3);if(index<2){await p.getByTestId('next').click();assert.equal((await state(p)).caseId,index+1);}else await p.getByTestId('closed-menu').click();}
 await p.reload();await p.waitForFunction(()=>!document.querySelector('[data-testid=case-2]').disabled);assert.equal(await p.getByTestId('case-2').isEnabled(),true);await p.getByTestId('case-0').click();await p.getByTestId('start').click();await p.getByTestId('hint').click();assert.equal((await state(p)).hints,1);await p.getByTestId('close-dialog').click();await p.getByTestId('place-mill').click();await p.getByTestId('spot-pantry').click();await p.getByTestId('examine').click();assert.equal((await state(p)).found.includes('pantry'),false);assert.equal(await p.getByRole('dialog').count(),0);
 await p.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal((await state(p)).paused,true);await p.getByTestId('carry-on').click();await p.getByTestId('menu').click();
 for(const[width,height]of[[320,568],[568,320],[390,844],[844,390]]){await p.setViewportSize({width,height});await p.getByTestId('start').click();await p.waitForTimeout(100);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${width}: no page overflow`);await p.getByTestId('spot-prints').scrollIntoViewIfNeeded();const box=await p.getByTestId('spot-prints').boundingBox(),cdp=await p.context().newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.equal((await state(p)).focus,null,'cancelled touch cannot select a clue');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();await p.getByTestId('examine').click();await p.getByTestId('close-dialog').click();await clue(p,CASES[0].clues.find(c=>c.id==='baker'));await pair(p,CASES[0].deductions[0]);if(width===390)await p.screenshot({path:out+'/pawprint-detectives-phone.png',fullPage:true});await p.getByTestId('menu').click();}
 assert.deepEqual(errors,[]);const broken=await browser.newPage();await broken.route('**/art/detectives/characters.png',r=>r.abort());await broken.goto(base+'/detectives');await broken.getByRole('button',{name:'Retry artwork'}).waitFor();assert.equal(await broken.getByTestId('start').isEnabled(),false);await broken.unroute('**/art/detectives/characters.png');await broken.getByRole('button',{name:'Retry artwork'}).click();await broken.getByTestId('start').click();assert.ok(await broken.getByTestId('village').isVisible());await broken.close();console.log('PASS Detectives: real clue collection, dialogue/follow-up, drag/tap pairing, all three case explanations, banked stars/unlocks, saved notebook, focus/pause, hints/gates, reduced motion, native touch/cancel, artwork retry and four phone layouts.');
}finally{await browser.close();}
