import assert from 'node:assert/strict';import{chromium}from'playwright';
const browser=await chromium.launch(),base=process.env.E2E_BASE_URL||'http://localhost:3000';
const kinds=['weasel','fox','owl','badger','cougar'];
try{
 const page=await browser.newPage({viewport:{width:1280,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/frontier');await page.waitForSelector('[data-art-ready="true"]');
 for(const kind of kinds){const extent=await page.evaluate(async name=>{const im=new Image();im.src='/art/frontier/enemy-'+name+'.png';await im.decode();const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(im,0,0);const d=ctx.getImageData(0,0,c.width,c.height).data;let left=c.width,top=c.height,right=0,bottom=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(d[(y*c.width+x)*4+3]>3){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}return{left,top,right:c.width-1-right,bottom:c.height-1-bottom,width:right-left+1,height:bottom-top+1};},kind);assert.ok(Math.min(extent.left,extent.top,extent.right,extent.bottom)>=8,kind+' has full transparent safety margins');assert.ok(extent.width>100&&extent.height>100);console.log(kind,extent);}
 await page.emulateMedia({reducedMotion:'reduce'});await page.getByTestId('map-1').click();
 await page.evaluate(types=>{const g=window.__frontier();for(let i=0;i<types.length;i++){const t=g.tile(4+i,4);t.seen=true;t.t='snow';t.f=types[i]==='cougar'?'lair':'den';t.den=types[i];}},kinds);await page.waitForTimeout(1800);
 // Click each den using the same automatic camera as the game.
 for(let i=0;i<kinds.length;i++){const at=await page.evaluate(x=>{const g=window.__frontier();let x0=13,y0=13,x1=0,y1=0;for(let y=0;y<13;y++)for(let xx=0;xx<13;xx++)if(g.tile(xx,y).seen){x0=Math.min(x0,xx);y0=Math.min(y0,y);x1=Math.max(x1,xx);y1=Math.max(y1,y);}x0-=1.5;y0-=1.5;x1+=2.5;y1+=2.5;const s=Math.min(13,Math.max(7,x1-x0,y1-y0)),cx=Math.max(0,Math.min(13-s,(x0+x1)/2-s/2)),cy=Math.max(0,Math.min(13-s,(y0+y1)/2-s/2));return[(10+(x+.5-cx)*624/s)/644,(10+(4+.5-cy)*624/s)/644];},4+i);const r=await page.getByTestId('map').boundingBox();await page.mouse.click(r.x+r.width*at[0],r.y+r.height*at[1]);await page.waitForTimeout(180);assert.ok(await page.locator('.ff-titled canvas').count());assert.match(await page.getByTestId('panel').innerText(),/Den power/);}
 assert.deepEqual(errors,[]);await page.close();console.log('PASS enemy artwork: five isolated complete sprites, transparent safety margins and all five den/inspector renderings.');
}finally{await browser.close();}
