import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const browser=await chromium.launch(),base=process.env.E2E_BASE_URL||'http://localhost:3000',out='/Users/jasonchua/Documents/Codex/2026-10-08/read/outputs';
const state=p=>p.evaluate(()=>{const g=window.__moonlight().game;return {time:g.time,paused:g.paused,active:g.active,state:g.state,catches:g.catches,collected:g.collected,rescued:g.rescued,friendHome:g.friendHome,hero:g.hero,heroes:g.heroes,trail:g.trail,treats:g.treats};});
const advance=(p,dt,input)=>p.evaluate(([dt,input])=>window.__moonlight().advance(dt,input),[dt,input]);
async function walk(p,label,to){await p.getByRole('button',{name:'Walk to '+label,exact:true}).click();const started=(await state(p)).time;let catches=(await state(p)).catches;
 for(let i=0;i<400;i++){const s=await state(p);if(Math.hypot(s.hero.x-to.x,s.hero.y-to.y)<24)return;assert.equal(s.state,'playing',`heist ended walking to ${label}`);if(s.catches!==catches){await p.getByRole('button',{name:'Walk to '+label,exact:true}).click();catches=s.catches;}if(await p.getByTestId('ability').isEnabled())await p.getByTestId('ability').click();await advance(p,.25);if((await state(p)).time-started>40)break;}
 assert.fail(`walk to ${label} stalled: ${JSON.stringify(await state(p))}`);
}
try {
 const p=await browser.newPage({viewport:{width:1536,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(20000);
 await p.goto(base);assert.equal(await p.locator('.arcade-card').count(),29);await p.getByRole('link',{name:/Moonlight Mischief/}).click();
 await p.getByTestId('start').click();await p.waitForFunction(()=>window.__moonlight()?.game);assert.equal((await state(p)).time,0);
 const cv=p.getByTestId('village'),r=await cv.boundingBox();await p.mouse.move(r.x+r.width*.2,r.y+r.height*.7);await p.mouse.down();await p.mouse.move(r.x+r.width*.3,r.y+r.height*.7);await p.mouse.up();assert.equal((await state(p)).time,0,'dragging the map never counts as a path tap');await p.mouse.click(r.x+r.width*.225,r.y+r.height*.465/640*1000);await p.waitForTimeout(200);assert.ok((await state(p)).time>0,'tapping a path starts navigation');
 await cv.focus();await p.keyboard.press('KeyQ');assert.equal((await state(p)).active,'enzo');await p.keyboard.press('Space');assert.ok((await state(p)).hero.cooldown>0);
 await p.keyboard.down('KeyD');await p.waitForTimeout(100);await p.evaluate(()=>window.dispatchEvent(new Event('blur')));await p.keyboard.up('KeyD');assert.ok((await state(p)).paused);const paused=(await state(p)).time;await p.waitForTimeout(100);assert.equal((await state(p)).time,paused);await p.getByTestId('carry-on').click();
 await p.getByTestId('menu').click();await p.reload();await p.getByTestId('resume').click();assert.ok((await state(p)).paused);assert.equal((await state(p)).active,'enzo');await p.getByTestId('carry-on').click();
 await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>!window.__moonlight().stage.motion);const clock=await p.evaluate(()=>window.__moonlight().stage.clock);await advance(p,.2,{x:1,y:0});await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>window.__moonlight().stage.clock),clock);await p.emulateMedia({reducedMotion:'no-preference'});
 await p.getByTestId('menu').click();await p.getByTestId('start').click();await p.getByTestId('choose-enzo').click();await p.locator('.mm-help summary').click();
 await walk(p,'Dry dust',{x:540,y:515});await p.getByTestId('interact').click();assert.ok((await state(p)).hero.dust>0);
 await walk(p,'Heavy obstacle',{x:650,y:412});await p.getByTestId('interact').click();
 await walk(p,'Rescue cage',{x:515,y:245});await p.getByTestId('interact').click();assert.ok((await state(p)).rescued);
 for(let i=0;i<7;i++){const s=await state(p),left=s.treats.filter(t=>!t.taken);if(!left.length)break;const target=[...left].sort((a,b)=>b.x-a.x)[0],index=left.indexOf(target)+1;await walk(p,'Treat '+index,target);}
 await walk(p,'Home',{x:205,y:190});await p.getByTestId('interact').click();await p.getByTestId('choose-dora').click();await walk(p,'Dora’s fence gap',{x:190,y:410});await p.getByTestId('interact').click();await walk(p,'Home',{x:205,y:190});await p.getByTestId('interact').click();
 await p.waitForFunction(()=>window.__moonlight().game.state==='won');assert.ok(JSON.parse(await p.evaluate(()=>localStorage.getItem('moonlight-mischief-v1'))).stars[0]>0);assert.equal(await p.evaluate(()=>localStorage.getItem('moonlight-mischief-run-v1')),null);await p.reload();await p.waitForFunction(()=>!document.querySelector('[data-testid=night-1]').disabled);assert.ok(await p.getByTestId('night-1').isEnabled());await p.getByTestId('night-1').click();await p.getByTestId('start').click();assert.equal(await p.evaluate(()=>window.__moonlight().game.night),1);
 await p.getByTestId('menu').click();await p.evaluate(()=>localStorage.setItem('moonlight-mischief-run-v1','broken'));await p.reload();assert.equal(await p.getByTestId('resume').count(),0);
 for(const [width,height] of [[320,568],[568,320],[390,844],[844,390]]){await p.setViewportSize({width,height});await p.getByTestId('start').click();await p.waitForTimeout(150);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${width}: no sideways overflow`);const pad=p.getByRole('button',{name:'Move →'});await pad.scrollIntoViewIfNeeded();const box=await pad.boundingBox(),cdp=await p.context().newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2}]});await p.waitForTimeout(100);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await cdp.detach();const at=(await state(p)).hero.x;await p.waitForTimeout(100);assert.equal((await state(p)).hero.x,at,'cancel releases paw pad');await p.getByTestId('pause').click();await p.getByTestId('carry-on').click();await p.screenshot({path:`.checks/moonlight-${width}x${height}.png`,fullPage:true});if(width===390)await p.screenshot({path:out+'/moonlight-mischief-phone.png',fullPage:true});await p.getByTestId('menu').click();}
 assert.deepEqual(errors,[]);
 const broken=await browser.newPage();await broken.route('**/art/moonlight/village.png',route=>route.abort());await broken.goto(base+'/moonlight');await broken.getByRole('button',{name:'Retry artwork'}).waitFor();assert.equal(await broken.getByTestId('start').isEnabled(),false);await broken.unroute('**/art/moonlight/village.png');await broken.getByRole('button',{name:'Retry artwork'}).click();await broken.getByTestId('start').click();assert.ok(await broken.getByTestId('village').isVisible());await broken.close();
 console.log('PASS Moonlight Mischief: real tap/keyboard/ability controls, interrupted input, focus/pause, mid-heist resume, reduced motion, complete timed heist, banked results/unlock, corrupt saves, asset retry and four phone layouts.');
}finally{await browser.close();}
