import assert from'node:assert/strict';import{chromium}from'playwright';
const b=await chromium.launch(),base=process.env.E2E_BASE_URL||'http://localhost:3000';
try{const p=await b.newPage({viewport:{width:1366,height:768}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/moonpond');await p.getByTestId('start').click();await p.waitForSelector('[data-art-ready="true"]');
 const stats=await p.evaluate(()=>window.__moonpond().art.inspect());assert.equal(stats.filter(s=>s.name.startsWith('creature')).length,40);assert.ok(stats.every(s=>s.pixels>25));console.log('Crop boundaries:',stats.filter(s=>s.edge).map(s=>s.name));assert.ok(stats.every(s=>!s.edge),'every effective sprite has an alpha gutter');
 const act=await p.getByTestId('act').boundingBox();assert.ok(act.y+act.height<=768,'a tall sidebar cannot displace the hold button');
 await p.evaluate(()=>{window.__moonpond().game.shells=1000;});await p.getByTestId('shop').click();await p.getByTestId('buy-line').click();await p.getByTestId('buy-line').click();await p.getByTestId('close').click();
 await p.keyboard.down('Space');await p.waitForFunction(()=>window.__moonpond().game.charge>.4);await p.keyboard.up('Space');await p.waitForFunction(()=>window.__moonpond().game.state==='waiting');
 await p.evaluate(()=>{const g=window.__moonpond().game;g.bite.id='reed-skipper';g.bite.nibbles=[];g.bite.at=g.clock+.5;});await p.waitForFunction(()=>window.__moonpond().game.biting);await p.keyboard.down('Space');await p.waitForFunction(()=>window.__moonpond().game.state==='hooked');await p.getByTestId('tension').waitFor();const band=await p.locator('.mp-safe').getAttribute('style');assert.match(band,/left: 34%/);assert.match(band,/width: 42%/);assert.equal(await p.locator('meter').evaluate(m=>m.high),.76);await p.keyboard.up('Space');
 await p.close();assert.deepEqual(errors,[]);
 const retry=await b.newPage();let blocked=true;await retry.route('**/art/moonpond/heroes.png',r=>blocked?r.abort():r.continue());await retry.goto(base+'/moonpond');await retry.getByTestId('start').click();await retry.getByRole('button',{name:'Retry artwork'}).waitFor();assert.equal(await retry.getByTestId('pond').count(),1);blocked=false;await retry.getByRole('button',{name:'Retry artwork'}).click();await retry.waitForSelector('[data-art-ready="true"]');assert.equal(await retry.getByRole('button',{name:'Retry artwork'}).count(),0);await retry.close();
 console.log('PASS painted Moonpond: 40 complete creature silhouettes, safe hero/prop crops, visible controls, live tension and playable failed-asset retry.');
}finally{await b.close();}
