import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const b=await chromium.launch(),base=process.env.E2E_BASE_URL||'http://localhost:3000',errors=[];
try{
 const p=await b.newPage({viewport:{width:390,height:844}});p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(20000);
 await p.goto(base+'/moonlight');await p.getByTestId('start').waitFor();await p.waitForFunction(()=>!document.querySelector('[data-testid=start]').disabled);
 assert.equal(await p.getByTestId('night-2').isEnabled(),false);await p.getByTestId('practice').check();assert.equal(await p.getByTestId('night-2').isEnabled(),true);await p.getByTestId('night-2').click();await p.getByRole('radio',{name:'Before dawn'}).check();assert.ok(await p.getByTestId('night-0').evaluate(e=>e.classList.contains('selected')),'returning to timed mode respects unlocks');
 await p.getByTestId('practice').check();await p.getByTestId('night-2').click();await p.getByTestId('start').click();assert.equal(await p.evaluate(()=>window.__moonlight().game.night),2);assert.equal(await p.evaluate(()=>window.__moonlight().game.mode),'practice');
 await p.getByTestId('choose-enzo').click();assert.ok(await p.getByTestId('village').evaluate(e=>e===document.activeElement),'choosing a hero restores keyboard focus');const before=await p.evaluate(()=>window.__moonlight().game.hero.x);await p.keyboard.down('KeyD');await p.waitForTimeout(160);await p.keyboard.up('KeyD');assert.ok(await p.evaluate(x=>window.__moonlight().game.hero.x>x+4,before));
 await p.getByTestId('creep').click();assert.equal(await p.getByTestId('creep').getAttribute('aria-pressed'),'true');assert.ok(await p.getByTestId('village').evaluate(e=>e===document.activeElement));await p.getByTestId('creep').click();
 await p.getByTestId('zoom').click();await p.waitForTimeout(400);assert.ok(await p.locator('.mm-map').evaluate(e=>e.scrollHeight>e.clientHeight&&e.scrollWidth>e.clientWidth),'zoom is contained in a scrollable viewport');
 await p.locator('.mm-help summary').click();await p.getByRole('button',{name:'Walk to Dry dust',exact:true}).click();await p.evaluate(()=>{const t=window.__moonlight();for(let i=0;i<55;i++)t.advance(.1);});await p.waitForTimeout(500);
 const camera=await p.evaluate(()=>{const t=window.__moonlight(),v=document.querySelector('.mm-map'),c=document.querySelector('[data-testid=village]');return {x:t.game.hero.x/1000*c.clientWidth-v.scrollLeft,y:t.game.hero.y/640*c.clientHeight-v.scrollTop,w:v.clientWidth,h:v.clientHeight,left:v.scrollLeft,top:v.scrollTop};});assert.ok(camera.left>100&&camera.top>40);assert.ok(camera.x>0&&camera.x<camera.w&&camera.y>0&&camera.y<camera.h,'zoom follows the selected chinchilla');
 const map=p.locator('.mm-map');await map.scrollIntoViewIfNeeded();const mb=await map.boundingBox(),panBefore=await map.evaluate(e=>e.scrollLeft);await p.mouse.move(mb.x+mb.width*.6,mb.y+mb.height*.5);await p.mouse.down();await p.mouse.move(mb.x+mb.width*.6+55,mb.y+mb.height*.5,{steps:5});await p.mouse.up();const panAfter=await map.evaluate(e=>e.scrollLeft);assert.ok(panAfter<panBefore-30,'mouse dragging pans the zoomed map');await p.waitForTimeout(100);assert.equal(await map.evaluate(e=>e.scrollLeft),panAfter,'camera yields to manual panning');
 await p.getByTestId('pause').click();const dialog=p.getByRole('dialog',{name:'Heist paused'});assert.ok(await dialog.isVisible());const d=await dialog.boundingBox(),v=await p.locator('.mm-map-frame').boundingBox();assert.ok(d.x>=v.x-1&&d.x+d.width<=v.x+v.width+1,'pause stays inside zoom viewport');await p.keyboard.press('Shift+Tab');assert.ok(await p.getByTestId('overlay-menu').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');assert.ok(await p.getByTestId('carry-on').evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>window.__moonlight().game.paused),false);
 await p.emulateMedia({reducedMotion:'reduce'});await p.getByTestId('menu').click();await p.getByTestId('start').click();assert.equal(await p.evaluate(()=>window.__moonlight().stage.motion),false,'new heists retain reduced motion');await p.getByTestId('zoom').click();await p.waitForTimeout(100);assert.ok(await p.locator('.mm-map').evaluate(e=>e.scrollTop>0),'reduced motion camera snaps without decoration');
 await p.getByTestId('menu').click();await p.getByRole('radio',{name:'Before dawn'}).check();await p.getByTestId('start').click();await p.getByTestId('ability').click();await p.waitForTimeout(180);assert.ok(await p.evaluate(()=>window.__moonlight().game.hero.x>160),'ability button dashes without holding a direction');
 assert.deepEqual(errors,[]);console.log('PASS Moonlight polish: all-night practice, timed unlocks, action focus, standstill dash, creep toggle, zoom following, zoom pause, focus trap, and reduced-motion restarts.');
}finally{await b.close();}
