import assert from'node:assert/strict';import{mkdir}from'node:fs/promises';import{chromium}from'playwright';
const b=await chromium.launch(),base=process.env.E2E_BASE_URL||'http://localhost:3000',out='.checks/pinball';await mkdir(out,{recursive:true});
const state=p=>p.evaluate(()=>{const g=window.__pinball().game;return{state:g.state,paused:g.paused,time:g.time,angles:g.angles,score:g.score,charge:g.charge,charging:g.charging,seed:g.seed,balls:g.balls,ballNo:g.ballNo};});
try{
 const p=await b.newPage({viewport:{width:1536,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(20000);await p.goto(base);assert.equal(await p.locator('.arcade-card').count(),28);await p.getByRole('link',{name:/Pawprint Pinball/}).click();await p.waitForFunction(()=>!document.querySelector('[data-testid="start"]').disabled);await p.getByTestId('start').hover();await p.waitForTimeout(250);assert.deepEqual(await p.getByTestId('start').evaluate(e=>{const c=getComputedStyle(e);return[c.backgroundColor,c.color];}),['rgb(255, 231, 182)','rgb(40, 22, 38)'],'the gold button stays gold with dark lettering under the mouse');await p.getByTestId('start').click();await p.waitForFunction(()=>window.__pinball()?.game);
 const launch=p.getByTestId('launch');await launch.scrollIntoViewIfNeeded();let box=await launch.boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.waitForTimeout(220);assert.ok((await state(p)).charge>.1);await launch.dispatchEvent('pointercancel',{pointerId:1,pointerType:'mouse'});await p.mouse.up();await p.waitForTimeout(100);assert.equal((await state(p)).state,'ready');assert.equal((await state(p)).charge,0,'cancelled launch never fires');
 await p.getByTestId('table').focus();await p.keyboard.down('ArrowLeft');await p.keyboard.down('ArrowRight');let s;await p.waitForFunction(()=>{const s=window.__pinball().game;return s.angles[0]<0&&s.angles[1]>Math.PI;});await p.keyboard.up('ArrowLeft');await p.waitForFunction(()=>{const s=window.__pinball().game;return s.angles[0]>.4&&s.angles[1]>Math.PI;});await p.keyboard.up('ArrowRight');
 await p.keyboard.down('Space');await p.waitForTimeout(700);assert.ok((await state(p)).charge>.4);assert.ok(await p.evaluate(()=>window.__pinball().stage.inspect().pull)>.4,'the plunger draws back with the charge');await p.keyboard.up('Space');await p.waitForTimeout(100);assert.equal((await state(p)).state,'play');assert.equal((await state(p)).balls.length,1);
 await p.keyboard.down('ArrowLeft');await p.evaluate(()=>window.dispatchEvent(new Event('blur')));await p.keyboard.up('ArrowLeft');assert.ok((await state(p)).paused);const paused=(await state(p)).time;await p.waitForTimeout(100);assert.equal((await state(p)).time,paused);await p.getByTestId('carry-on').click();
 const seed=(await state(p)).seed;await p.getByTestId('menu').click();await p.reload();await p.getByTestId('resume').click();assert.ok((await state(p)).paused);assert.equal((await state(p)).seed,seed);await p.getByTestId('carry-on').click();
 await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>!window.__pinball().stage.motion);const clock=await p.evaluate(()=>window.__pinball().stage.clock);await p.evaluate(()=>window.__pinball().advance(.3));assert.equal(await p.evaluate(()=>window.__pinball().stage.clock),clock);await p.emulateMedia({reducedMotion:'no-preference'});
 const played=await p.evaluate(()=>{const t=window.__pinball(),g=t.game;for(let i=0;i<600&&!g.ended;i++){if(g.state==='ready'){t.advance(.95,{left:false,right:false,launch:true});t.advance(.025);}if(g.balls.some(b=>!b.rail&&Math.hypot(b.vx,b.vy)<25)&&g.time>=g.nudgeUntil&&g.time>=g.tiltUntil)g.nudge();t.advance(.5);}return{ended:g.ended,score:g.score};});assert.ok(played.ended,'three real drains finish the arcade run');assert.ok(played.score>0);await p.getByRole('dialog',{name:'Run complete'}).waitFor();const record=await p.evaluate(()=>JSON.parse(localStorage.getItem('pawprint-pinball-v1')));assert.ok(record.best>=played.score);assert.equal(record.games,1);assert.equal(await p.evaluate(()=>localStorage.getItem('pawprint-pinball-run-v1')),null);await p.reload();assert.equal(await p.getByTestId('resume').count(),0);
 await p.getByTestId('practice').check();for(const[width,height]of[[320,568],[568,320],[390,844],[844,390]]){await p.setViewportSize({width,height});await p.getByTestId('start').click();await p.waitForTimeout(100);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${width}: no horizontal overflow`);await p.getByTestId('left').scrollIntoViewIfNeeded();const l=await p.getByTestId('left').boundingBox(),r=await p.getByTestId('right').boundingBox();await p.getByTestId('left').evaluate(el=>el.addEventListener('pointerdown',e=>window.__pinLeft=e.pointerId,{once:true}));const cdp=await p.context().newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:l.x+l.width/2,y:l.y+l.height/2,id:11},{x:r.x+r.width/2,y:r.y+r.height/2,id:22}]});await p.waitForFunction(()=>{const s=window.__pinball().game;return s.angles[0]<0&&s.angles[1]>Math.PI;});const id=await p.evaluate(()=>window.__pinLeft);await p.getByTestId('left').dispatchEvent('pointercancel',{pointerId:id,pointerType:'touch'});await p.waitForFunction(()=>{const s=window.__pinball().game;return s.angles[0]>.4&&s.angles[1]>Math.PI;});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await cdp.detach();await p.waitForFunction(()=>{const s=window.__pinball().game;return s.angles[0]>.4&&s.angles[1]<Math.PI;});await p.getByTestId('pause').click();await p.keyboard.press('Escape');assert.equal((await state(p)).paused,false);if(width===390)await p.screenshot({path:out+'/pawprint-pinball-phone.png',fullPage:true});await p.getByTestId('menu').click();}
 assert.deepEqual(errors,[]);const broken=await b.newPage();await broken.route('**/art/pinball/pieces.png',r=>r.abort());await broken.goto(base+'/pinball');await broken.getByRole('button',{name:'Retry artwork'}).waitFor();assert.equal(await broken.getByTestId('start').isEnabled(),false);await broken.unroute('**/art/pinball/pieces.png');await broken.getByRole('button',{name:'Retry artwork'}).click();await broken.getByTestId('start').click();assert.ok(await broken.getByTestId('table').isVisible());await broken.close();
 console.log('PASS Pinball: menu, real keyboard/launch, cancelled launch, independent flippers, focus/pause, saved physics, reduced motion, full three-ball run, banked records, native dual touch/cancel, artwork retry and four phone layouts.');
}finally{await b.close();}
