import assert from'node:assert/strict';import{Game,CASES}from'../.checks/detectives-game.js';
export function investigate(index,order=false,check=()=>{}){const g=new Game(index);let turns=0;while(!g.complete&&turns++<10){let progress=false;const clues=order?[...g.case.clues].reverse():g.case.clues;for(const c of clues){if(!g.required.includes(c.id)||g.found.includes(c.id)||!g.available(c))continue;g.move(c.place);g.hero(c.kind==='scent'?'enzo':'dora');g.select(c.id);assert.ok(c.kind==='talk'?g.ask(c.id):g.inspect(c.id));check(g);progress=true;}for(const d of g.case.deductions){if(g.deduced.includes(d.id)||!d.pair.every(id=>g.found.includes(id)))continue;assert.ok(g.choosePair(...d.pair));assert.ok(g.connect(d.answer));check(g);progress=true;}assert.ok(progress,`case ${index}: no soft lock`);}assert.ok(g.complete);return g;}
for(let index=0;index<CASES.length;index++){
 const g=new Game(index),c=g.case;assert.equal(new Set(c.clues.map(c=>c.id)).size,c.clues.length);assert.equal(new Set(c.deductions.map(d=>d.id)).size,c.deductions.length);for(const d of c.deductions){assert.equal(d.pair.length,2);assert.ok(d.pair.every(id=>c.clues.some(c=>c.id===id)));assert.ok(d.answer>=0&&d.answer<3);}
 assert.equal(g.explain(c.solution),false,'answers alone cannot skip investigation');assert.equal(g.choosePair(c.deductions[0].pair[0],c.deductions[0].pair[1]),false,'unfound clues cannot be linked');assert.ok(Game.load(g.save())?.paused);
 const look=c.clues.find(c=>c.kind==='look'&&!c.need);g.move(look.place);g.hero('enzo');assert.equal(g.inspect(look.id),null);g.hero('dora');assert.ok(g.inspect(look.id));const count=g.found.length;assert.ok(g.inspect(look.id));assert.equal(g.found.length,count,'re-reading never duplicates evidence');
 const locked=c.clues.find(c=>c.need&&c.need!==look.id);g.move(locked.place);assert.equal(g.inspect(locked.id),null,'context gates must be earned');
 const scent=c.clues.find(c=>c.kind==='scent');g.move(scent.place);g.hero('dora');assert.equal(g.inspect(scent.id),null);
 let snapshots=0;const done=investigate(index,false,run=>{snapshots++;const copy=Game.load(run.save());assert.ok(copy?.paused);copy.pause(false);assert.equal(copy.save(),run.save());});const reversed=investigate(index,true);assert.deepEqual(new Set(reversed.deduced),new Set(done.deduced),'exploration order does not change the case');
 const d=done.case.deductions[0],review=Game.load(done.save());review.pause(false);review.choosePair(...d.pair);const before=review.mistakes;assert.equal(review.connect((d.answer+1)%3),false);assert.equal(review.mistakes,before,'reviewing a proved fact cannot cost a star');
 let accepted=0;for(let a=0;a<3;a++)for(let b=0;b<3;b++)for(let e=0;e<3;e++){const copy=Game.load(done.save());copy.pause(false);const ok=copy.explain([a,b,e]);accepted+=Number(ok);assert.equal(ok,[a,b,e].every((v,i)=>v===c.solution[i]));}assert.equal(accepted,1,'exactly one complete explanation follows the evidence');
 assert.ok(done.explain(c.solution));assert.equal(done.state,'closed');assert.equal(done.stars,3);assert.equal(Game.load(done.save()),null);assert.equal(done.explain(c.solution),false);console.log(`Case ${index+1}: ${snapshots} action snapshots, forward/reverse exploration and unique explanation pass.`);
}
{
 const g=new Game();g.pause(true);const saved=g.save();assert.equal(g.move('mill'),false);assert.equal(g.select('prints'),false);assert.equal(g.inspect('prints'),null);assert.equal(g.hint(),'');assert.equal(g.save(),saved);g.pause(false);const hint=g.hint();assert.match(hint,/Dora/);assert.equal(g.hints,1);
 const finished=investigate(0);const def=finished.case.deductions[0],mistake=new Game();for(const id of def.pair){const c=mistake.case.clues.find(c=>c.id===id);mistake.move(c.place);mistake.hero('dora');if(c.kind==='talk')mistake.ask(id);else mistake.inspect(id);}mistake.choosePair(...def.pair);assert.equal(mistake.connect((def.answer+1)%3),false);assert.equal(mistake.mistakes,1);assert.ok(mistake.connect(def.answer));
 const npc=finished.case.clues.find(c=>c.id==='milo');finished.move(npc.place);assert.ok(finished.ask(npc.id,true));assert.match(finished.speech,/pantry/);
 for(const patch of[{v:2},{caseId:99},{state:'closed'},{place:'sea'},{who:'owl'},{found:['unknown']},{deduced:['visitor']},{pair:['prints','prints']},{mistakes:-1},{hints:Infinity}]){const s=JSON.parse(g.save());Object.assign(s,patch);assert.equal(Game.load(JSON.stringify(s)),null);}const s=JSON.parse(g.save());s.found=['pantry'];assert.equal(Game.load(JSON.stringify(s)),null);assert.equal(Game.load('broken'),null);
}
console.log('Pawprint Detectives: all cases, clue abilities, witness follow-ups, dependency gates, supported links, unique solutions, hints, pause, snapshots and malformed saves pass.');
