'use client';
import {useEffect,useRef,useState} from 'react';
import {FlappyGame,FLIGHT} from '../lib/flappy-game';
import {drawFlight} from '../lib/flappy-scene';
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),game=useRef(new FlappyGame(42)),last=useRef(0),[frame,setFrame]=useState(0),[best,setBest]=useState(0),[error,setError]=useState(false);const g=game.current;
 function flap(){game.current.flap();canvas.current?.focus();setFrame(v=>v+1)}
 function restart(){game.current=new FlappyGame();game.current.flap();canvas.current?.focus();setFrame(v=>v+1)}
 function pause(){game.current.pause();canvas.current?.focus();setFrame(v=>v+1)}
 useEffect(()=>{const c=canvas.current?.getContext('2d');if(!c){setError(true);return}let raf=0,acc=0,ui=0;const loop=(now:number)=>{acc+=last.current?Math.min(.1,(now-last.current)/1000):0;last.current=now;while(acc>=1/120){game.current.step(1/120);acc-=1/120}drawFlight(c,game.current,now/1000);if(now-ui>70){setFrame(v=>v+1);setBest(b=>Math.max(b,game.current.score));ui=now}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('button,a,input'))return;if(['Space','ArrowUp','KeyW'].includes(e.code)){e.preventDefault();if(!e.repeat)flap()}if(e.code==='KeyP'||e.code==='Escape'){e.preventDefault();if(!e.repeat)pause()}};const blur=()=>{if(game.current.state==='playing')game.current.pause()};window.addEventListener('keydown',down);window.addEventListener('blur',blur);return()=>{cancelAnimationFrame(raf);last.current=0;window.removeEventListener('keydown',down);window.removeEventListener('blur',blur)}},[]);
 void frame;
 return <main className="flight-shell"><header className="flight-header"><a href="/">Chin x Pit <span>BORDER HOP</span></a><span>DORA + ENZO · TRAVEL TOGETHER</span></header><section className="flight-heading"><div><p className="flight-eyebrow">TWO CHINCHILLAS. ONE BIG TRIP.</p><h1>Little wings.<br/><em>Big American dream.</em></h1></div><p>Flap through the desert checkpoints.<br/>Get both friends through 20 gaps to reach<br/>the Welcome to the USA gate.</p></section>
 <section className="flight-board" aria-label="Border Hop game"><div className="flight-hud"><div><small>CHECKPOINTS</small><strong>{g.score}<span> / {FLIGHT.goal}</span></strong></div><div className="flight-route"><span>DESERT</span><div><i style={{width:g.score/FLIGHT.goal*100+'%'}}/></div><span>USA ★</span></div><div><small>SESSION BEST</small><strong>{best}</strong></div><button onClick={pause} disabled={g.state!=='playing'&&g.state!=='paused'} aria-label={g.state==='paused'?'Resume game':'Pause game'}>{g.state==='paused'?'▶':'Ⅱ'}</button></div>
 <div className="flight-canvas-wrap"><canvas ref={canvas} width={900} height={540} tabIndex={0} aria-label="Dora and Enzo fly together. Press Space, Up, or tap to flap. Avoid checkpoint columns and the ground." onPointerDown={e=>{e.preventDefault();flap()}}/>
 {(g.state==='ready'||g.state==='paused'||g.state==='lost'||g.state==='won'||error)&&<div className={'flight-overlay '+(g.state==='ready'?'flight-ready':'')}><div><span className="flight-eyebrow">{error?'CANVAS UNAVAILABLE':g.state==='won'?'ARRIVAL STAMP · USA':g.state==='lost'?'A LITTLE TURBULENCE':g.state==='paused'?'TAKE A BREATHER':'PASSPORTS? PAWS-PORTS.'}</span><h2>{error?'Please try another browser.':g.state==='won'?'Welcome, Dora & Enzo!':g.state==='lost'?'One more hop?':g.state==='paused'?'Trip paused.':'Ready for takeoff?'}</h2><p>{g.state==='won'?'All 20 checkpoints cleared. Two friends, one happy landing.':g.state==='lost'?`You cleared ${g.score} of 20 checkpoints. Keep both fluffy travelers inside the gaps.`:g.state==='paused'?'Dora and Enzo are waiting for you.':'One tap lifts both chinchillas. Release to glide down.'}</p>{!error&&<button className="flight-primary" onClick={g.state==='ready'?flap:g.state==='paused'?pause:restart}>{g.state==='ready'?'Let’s flap →':g.state==='paused'?'Continue the trip →':'Fly again →'}</button>}</div></div>}
 </div><div className="flight-controls"><span><kbd>SPACE</kbd> / <kbd>↑</kbd> / TAP to flap</span><span><kbd>P</kbd> pause · Both friends must clear each gap</span></div></section>
 <section className="flight-bottom"><div><span className="flight-portrait flight-dora">D</span><p><b>Dora</b><span>White fluff. Front-seat flyer.</span></p><span className="flight-portrait flight-enzo">E</span><p><b>Enzo</b><span>Grey fluff. Never left behind.</span></p></div><p>A desert postcard starring Dora & Enzo.<br/>Paper wings. Shared dreams. One more try.</p></section></main>
}
