'use client';
import {useEffect,useRef,useState} from 'react';
import {EscapeGame} from '../lib/escape-game';
import type {EscapeScene} from '../lib/escape-scene';
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),game=useRef(new EscapeGame()),scene=useRef<EscapeScene|null>(null),keys=useRef(new Set<string>()),[tick,setTick]=useState(0),[ready,setReady]=useState(false),[error,setError]=useState('');const g=game.current;
 function start(){game.current=new EscapeGame();game.current.start();keys.current.clear();canvas.current?.focus();setTick(t=>t+1)}
 function pause(){game.current.pause();keys.current.clear();canvas.current?.focus();setTick(t=>t+1)}
 function action(a:'interact'|'jump'|'decoy'){if(a==='interact')game.current.interact();if(a==='jump')game.current.jump();if(a==='decoy')game.current.distract();canvas.current?.focus();setTick(t=>t+1)}
 useEffect(()=>{let dead=false,raf=0,last=0,acc=0,ui=0;const resize=()=>scene.current?.resize();import('../lib/escape-scene').then(({EscapeScene})=>{if(dead||!canvas.current)return;try{scene.current=new EscapeScene(canvas.current);setReady(true);const loop=(now:number)=>{acc+=last?Math.min(.1,(now-last)/1000):0;last=now;while(acc>=1/120){const sx=+(keys.current.has('d')||keys.current.has('arrowright'))-+(keys.current.has('a')||keys.current.has('arrowleft')),sz=+(keys.current.has('s')||keys.current.has('arrowdown'))-+(keys.current.has('w')||keys.current.has('arrowup'));game.current.step(1/120,{x:(sx+sz)*Math.SQRT1_2,z:(sz-sx)*Math.SQRT1_2,sneak:keys.current.has('shift')});acc-=1/120}scene.current!.render(game.current,now/1000);if(now-ui>65){setTick(t=>t+1);ui=now}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);window.addEventListener('resize',resize)}catch{setError('This escape needs WebGL 2. Enable hardware acceleration and reload.')}}).catch(()=>setError('The escape could not load. Please reload.'));const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('button,a,input'))return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.current.add(k);if(e.repeat)return;if(k==='e')action('interact');if(k===' ')action('jump');if(k==='q')action('decoy');if(k==='p'||k==='escape')pause()};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>{keys.current.clear();if(game.current.active)game.current.pause()};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{dead=true;cancelAnimationFrame(raf);scene.current?.dispose();window.removeEventListener('resize',resize);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur)}},[]);
 const hold=(key:string,label:string)=><button onPointerDown={e=>{e.preventDefault();keys.current.add(key);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={()=>keys.current.delete(key)} onPointerCancel={()=>keys.current.delete(key)} onLostPointerCapture={()=>keys.current.delete(key)}>{label}</button>;void tick;
 return <main className="escape-shell"><header className="escape-header"><div><span>ENZO AND DORA</span><h1>Escapes from ICE</h1></div><button onClick={pause} disabled={!['playing','paused'].includes(g.state)}>{g.state==='paused'?'Resume':'Pause'} · P</button></header><div className="escape-layout"><section className="escape-stage" aria-label="Isometric chinchilla stealth escape"><canvas ref={canvas} tabIndex={0} aria-label="Move both chinchillas with WASD or arrows, E interact, Shift sneak, Q dust decoy"/><div className="escape-top"><span>{g.phase==='cage'?'01 · THE CAGE':'02 · THE WATCH ROOM'}</span><b>{Math.floor(g.time/60)}:{String(Math.floor(g.time%60)).padStart(2,'0')}</b></div>{g.active&&<div className="escape-objective"><small>NEXT MOVE</small><b>{g.objective}</b></div>}
 {g.phase==='room'&&g.active&&<div className="escape-alert"><span>{g.hidden?'HIDDEN':g.noticed?'YOU’RE BEING SEEN':g.alert>0?'BREAK LINE OF SIGHT':'KEEP LOW'}</span><div><i style={{width:g.alert*100+'%',background:g.noticed?'#e58870':'#d8bf83'}}/></div></div>}
 {g.active&&g.nearTarget&&<button className="escape-interact" onClick={()=>action('interact')}>E · {g.phase==='room'?(g.badge?'Escape together':'Take exit card'):g.key?'Unlock cage':g.stick?'Open hideout':'Search tunnel'}</button>}
 {g.active&&g.messageTime>0&&<div className="escape-message">{g.message}</div>}
 {(g.state==='ready'||g.state==='paused'||g.state==='caught'||g.state==='won'||error)&&<div className="escape-overlay"><div><span className="escape-eyebrow">{error?'WEBGL UNAVAILABLE':g.state==='caught'?'SPOTTED':g.state==='won'?'TOGETHER. ALWAYS.':g.state==='paused'?'STAY STILL':'A TWO-CHINCHILLA STEALTH ESCAPE'}</span><h2>{error?'A moment in the dark.':g.state==='caught'?'Back to the shadows.':g.state==='won'?'Two fluffs.\nOne freedom.':g.state==='paused'?'Take a breath.':'Small paws.\nQuiet escape.'}</h2><p>{error||(g.state==='caught'?'The agents spotted the pair. Retry from the opened cage; the room patrol resets.':g.state==='won'?`Enzo and Dora made it out together in ${Math.floor(g.time/60)}m ${Math.floor(g.time%60)}s.`:g.state==='paused'?'The patrols are paused.':'Search the blue tunnel. Solve the cage latch. Then slip past ICE patrols and get both friends to the exit.')}</p>{!error&&<button className="escape-primary" disabled={!ready} onClick={g.state==='paused'?pause:g.state==='caught'?()=>{g.retry();keys.current.clear();canvas.current?.focus();setTick(t=>t+1)}:start}>{g.state==='paused'?'Continue →':g.state==='caught'?'Retry the room →':g.state==='won'?'Escape again →':ready?'Begin the escape →':'Opening the cage…'}</button>}<small>WASD move · E interact · Shift sneak</small></div></div>}
 </section><aside className="escape-sidebar"><span className="escape-eyebrow">NO ONE LEFT BEHIND</span><h2>Enzo & Dora</h2><p>Move as a pair. Leave as a pair.</p><div className="escape-plan"><span className="escape-eyebrow">ESCAPE PLAN</span>{[['Find a chew stick',g.stick],['Open the pink hideout',g.key],['Unlock the cage',g.phase==='room'],['Collect the exit card',g.badge],['Reach freedom',g.state==='won']].map(([label,done])=><div key={String(label)} className={done?'done':''}><span>{done?'✓':'○'}</span>{label}</div>)}</div><div className="escape-pocket"><span className="escape-eyebrow">DUST DECOYS</span><b>{g.decoys} / 3</b><p>Face a direction and press Q. A dust puff turns nearby guards away for a few seconds.</p><button onClick={()=>action('decoy')} disabled={!g.active||g.phase!=='room'||!g.decoys}>Q · Throw a dust decoy</button></div><img src="/art/cage-reference.jpg" alt="Enzo and Dora’s actual wooden cage, blue tunnel, pink hideout and wire door"/><small className="escape-caption">Inspired by their real cage.</small></aside></div><div className="escape-controls"><div>{hold('a','←')}{hold('w','↑')}{hold('s','↓')}{hold('d','→')}{hold('shift','SNEAK')}<button onClick={()=>action('interact')}>E · INTERACT</button><button onClick={()=>action('jump')}>SPACE · HOP</button></div><p>Gold rings mark the next puzzle. In the room, hold Shift beneath blue-tinted tables to hide. Cabinets block guard sight. Leave the vision cones before the alert meter fills.</p></div></main>
}
