import{Game,WIDTH,HEIGHT,type Art,type Who,type Event,type Place}from'./detectives-game';
type C=CanvasRenderingContext2D;type Crop={image:HTMLImageElement;x:number;y:number;w:number;h:number};type Point={x:number;y:number};
const images=new Map<string,HTMLImageElement>(),sprites=new Map<string,Crop>();let loading:Promise<void>|null=null;
function atlas(image:HTMLImageElement,regions:[string,number,number,number,number][]){const cv=document.createElement('canvas');cv.width=image.width;cv.height=image.height;const c=cv.getContext('2d')!;c.drawImage(image,0,0);const data=c.getImageData(0,0,cv.width,cv.height).data;for(const[key,x0,y0,w,h]of regions){let x=w,y=h,r=0,b=0;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++)if(data[((y0+yy)*cv.width+x0+xx)*4+3]>24){x=Math.min(x,xx);y=Math.min(y,yy);r=Math.max(r,xx);b=Math.max(b,yy);}if(r>x&&b>y)sprites.set(key,{image,x:x0+x,y:y0+y,w:r-x+1,h:b-y+1});}}
export function loadArt(){if(loading)return loading;loading=Promise.all(['bakery','market','mill','characters','clues','notebook'].map(key=>new Promise<void>((resolve,reject)=>{const im=new Image();im.onload=()=>{images.set(key,im);resolve();};im.onerror=()=>reject(new Error(`Could not load ${key}`));im.src=`/art/detectives/${key}.png`;}))).then(()=>{const h=images.get('characters')!,p=images.get('clues')!;atlas(h,[['dora',0,0,550,512],['enzo',550,0,500,512],['badger',1050,0,486,512],['owl',0,512,512,512],['mouse',512,512,512,512],['vole',1024,512,512,512]]);atlas(p,[['footprints',0,0,384,512],['basket',384,0,422,512],['thread',806,0,362,512],['letter',1168,0,368,512],['bell',0,512,384,512],['feather',384,512,384,512],['parcel',768,512,430,512],['scent',1198,512,338,512]]);
 for(const[key,x,y,w,hh]of[['face-dora',255,130,250,250],['face-enzo',745,65,295,260],['face-badger',1205,15,290,215],['face-owl',130,520,300,260],['face-mouse',685,555,290,255],['face-vole',1180,555,320,255]]as[string,number,number,number,number][])sprites.set(key,{image:h,x,y,w,h:hh});if(sprites.size<20)throw new Error('Incomplete detective artwork');}).catch(e=>{loading=null;throw e;});return loading;}
function sprite(c:C,key:string,x:number,y:number,w:number,h:number,face=1){const s=sprites.get(key);if(!s)return;c.save();c.translate(x,y);if(face<0){c.translate(w,0);c.scale(-1,1);}const k=Math.min(w/s.w,h/s.h);c.drawImage(s.image,s.x,s.y,s.w,s.h,(w-s.w*k)/2,h-s.h*k,s.w*k,s.h*k);c.restore();}
export function graphic(c:C,key:Art,w:number,h:number,face=false){c.clearRect(0,0,w,h);sprite(c,face&&sprites.has('face-'+key)?'face-'+key:key,0,0,w,h);}
function text(c:C,t:string,x:number,y:number,size=18,fill='#3b261a'){c.font=`600 ${size}px Georgia,serif`;c.textAlign='center';c.textBaseline='middle';c.fillStyle=fill;c.fillText(t,x,y);}
type Walk={from:Point;to:Point;at:number;face:number};
export class Stage{
 motion=typeof window==='undefined'||!matchMedia('(prefers-reduced-motion: reduce)').matches;clock=0;private place:Place|null=null;private poses:Record<Who,Point>={dora:{x:465,y:605},enzo:{x:560,y:490}};private walks=new Map<Who,Walk>();effects:(Event&{at:number})[]=[];
 feed(events:Event[],g:Game){if(g.place!==this.place){this.place=g.place;this.poses={dora:{x:465,y:605},enzo:{x:560,y:490}};this.walks.clear();}for(const e of events){if(e.t==='select'&&g.selected){const p=g.selected,to={x:Math.max(90,Math.min(WIDTH-75,p.x+(p.kind==='talk'?115:-70))),y:Math.min(HEIGHT-30,Math.max(405,p.y+(p.kind==='talk'?100:70)))};this.walks.set(g.who,{from:{...this.poses[g.who]},to,at:this.clock,face:to.x<this.poses[g.who].x?-1:1});}if(this.motion)this.effects.push({...e,at:this.clock});}this.effects=this.effects.slice(-40);}
 update(dt:number,g:Game,halt=false){if(g.paused||halt||g.state==='closed')return;if(this.motion)this.clock+=Math.min(.1,dt);else{this.effects=[];for(const[who,w]of this.walks)this.poses[who]=w.to;this.walks.clear();}for(const[who,w]of this.walks){const t=Math.min(1,(this.clock-w.at)/.8),k=t*t*(3-2*t);this.poses[who]={x:w.from.x+(w.to.x-w.from.x)*k,y:w.from.y+(w.to.y-w.from.y)*k};if(t>=1)this.walks.delete(who);}this.effects=this.effects.filter(e=>this.clock-e.at<1.1);}
 inspect(){return{clock:this.clock,motion:this.motion,poses:this.poses,walks:this.walks.size};}
 draw(c:C,w:number,h:number,dpr:number,g:Game){c.setTransform(dpr*w/WIDTH,0,0,dpr*h/HEIGHT,0,0);c.clearRect(0,0,WIDTH,HEIGHT);const bg=images.get(g.place);if(!bg||sprites.size<20)return;c.drawImage(bg,0,0,WIDTH,HEIGHT);
 if(g.place==='bakery'){c.save();c.translate(336,99);c.rotate(.1);text(c,'Willow Hearth',0,-9,22);text(c,'BAKERY',0,17,27);c.restore();text(c,'MARKET →',735,243,16);text(c,'OLD MILL →',736,275,16);}
 if(g.who==='enzo')for(const p of g.spots)if(p.kind==='scent'&&g.available(p)&&(g.found.includes(p.id)||g.focus===p.id)){c.save();c.strokeStyle='#ffe49b';c.shadowColor='#f4c566';c.shadowBlur=9;c.lineWidth=2;c.setLineDash([2,11]);c.lineDashOffset=this.motion?-this.clock*16:0;c.beginPath();c.moveTo(p.x,p.y);if(g.caseId===2)c.bezierCurveTo(p.x-70,p.y+10,450,390,390,360);else c.bezierCurveTo(p.x+65,p.y-65,850,410,900,350);c.stroke();c.restore();}
 for(const p of g.spots)if(p.kind!=='talk'&&g.available(p)){const size=p.art==='footprints'?110:p.kind==='scent'?38:p.art==='basket'?105:p.art==='bell'?90:65;sprite(c,p.art,p.x-size/2,p.y-size*.65,size,size*.8);}
 const actors:{y:number;draw:()=>void}[]=g.spots.filter(p=>p.kind==='talk').map(p=>({y:p.y,draw:()=>{sprite(c,p.art,p.x-82,p.y-205,164,210);}}));
 for(const who of['dora','enzo']as Who[]){const p=this.poses[who],walk=this.walks.get(who),bob=this.motion?walk?Math.abs(Math.sin(this.clock*11))*3:Math.sin(this.clock*2+(who==='enzo'?1:0))*.9:0;actors.push({y:p.y,draw:()=>{c.save();c.fillStyle='#3d251d33';c.beginPath();c.ellipse(p.x,p.y,39,9,0,0,Math.PI*2);c.fill();if(g.who===who){c.strokeStyle='#f7d28a';c.lineWidth=2;c.beginPath();c.ellipse(p.x,p.y+1,42,12,0,0,Math.PI*2);c.stroke();}sprite(c,who,p.x-80,p.y-155-bob,160,160,walk?.face??1);c.restore();}});}actors.sort((a,b)=>a.y-b.y).forEach(a=>a.draw());
 if(this.motion){for(let i=0;i<7;i++){const x=(i*137+this.clock*11)%WIDTH,y=100+(i*89+this.clock*9)%(HEIGHT-190);c.save();c.translate(x,y);c.rotate(this.clock*.7+i);c.fillStyle=i%2?'#c4803266':'#e7b46566';c.beginPath();c.ellipse(0,0,3,1.5,0,0,Math.PI*2);c.fill();c.restore();}}
 for(const e of this.effects){if(e.t!=='clue')continue;const p=g.case.clues.find(c=>c.id===e.id);if(!p||p.place!==g.place)continue;const age=this.clock-e.at;c.save();c.globalAlpha=Math.max(0,1-age/1.1);for(let i=0;i<7;i++){const a=i*Math.PI*2/7,r=15+age*26;text(c,'✧',p.x+Math.cos(a)*r,p.y-15+Math.sin(a)*r*.7,12,'#ffe8a3');}c.restore();}
 }
}
