/** Authored, deterministic deduction rules. Untimed; no DOM or hidden random answers. */
export const WIDTH=960,HEIGHT=680;
export type Who='dora'|'enzo';export type Place='bakery'|'market'|'mill';
export type Art='footprints'|'basket'|'thread'|'letter'|'bell'|'feather'|'parcel'|'scent'|'dora'|'enzo'|'badger'|'owl'|'mouse'|'vole';
export type Clue={id:string;title:string;description:string;art:Art;place:Place;x:number;y:number;kind:'look'|'scent'|'talk';need?:string;source?:string;question?:string;quote?:string;followup?:string};
export type Deduction={id:string;pair:[string,string];title:string;choices:[string,string,string];answer:number;reason:string};
export type Case={id:string;name:string;intro:string;clues:Clue[];deductions:Deduction[];questions:[string,string,string];answers:[string[],string[],string[]];solution:[number,number,number];ending:string};
export const PLACES:Record<Place,{name:string;description:string}>={bakery:{name:'Bakery Square',description:'Warm ovens, tidy steps and a path toward the old mill.'},market:{name:'Market Lane',description:'Festival stalls, the clock tower and plenty of neighbours.'},mill:{name:'Old Mill Court',description:'A quiet pantry, flour sacks and a sheltered roost.'}};
const C=(id:string,title:string,description:string,art:Art,place:Place,x:number,y:number,kind:Clue['kind']='look',extra:Partial<Clue>={}):Clue=>({id,title,description,art,place,x,y,kind,...extra});
const D=(id:string,a:string,b:string,title:string,choices:[string,string,string],answer:number,reason:string):Deduction=>({id,pair:[a,b],title,choices,answer,reason});
export const CASES:Case[]=[{
 id:'moonberry',name:'The Missing Moonberry',intro:'The festival moonberry has vanished from the bakery steps. Find where it went, who moved it, and why.',
 clues:[
 C('prints','Flour pawprints','Fresh flour prints from a paw-patterned boot tread cross the bakery steps. The right tread has a crescent-shaped nick. The prints lie over the baker’s freshly swept doorstep.','footprints','bakery',570,555),
 C('basket','Broken basket','The moonberry basket has a split bottom slat. Purple stains and one berry stalk lie beneath the break; it could not safely carry the large moonberry.','basket','bakery',235,535),
 C('baker','Baker’s statement','Bruna swept the doorstep at sunset and checked it as she closed. There were no flour prints at that moment. She left the festival basket on the steps.','badger','bakery',150,370,'talk',{source:'Bruna the baker',question:'When did you close?',quote:'I swept the steps at sunset. They were clean when I closed.',followup:'Someone crossed the steps afterwards. Milo was carrying flour earlier; you can ask him about his boots.'}),
 C('trail','Berry scent trail','Enzo finds a continuous moonberry scent from the broken basket along the old mill path. It does not lead toward the market.','scent','bakery',700,455,'scent',{need:'basket'}),
 C('milo','Milo’s statement','Milo says his paw-patterned right boot tread has a crescent-shaped nick, and nobody else wears it. He says he did not go inside the bakery after sunset.','mouse','mill',285,370,'talk',{source:'Milo the mill helper',question:'Were you near the bakery?',quote:'My right boot has that little nick. I never went inside the bakery.',followup:'I stayed outside. The split basket spilled the moonberry, so I put it on the pantry shelf. My note is beside it.'}),
 C('pantry','Pantry message','A note beside the intact moonberry says: “Found it rolling beside the split basket. Put it on the pantry shelf so it would not roll away. I’ll return it after mending the basket. — Milo”.','letter','mill',450,540,'look',{need:'visitor'}),
 C('wren','Festival organiser’s note','Wren saw the basket on the steps at sunset. Nobody was asked to hide the festival moonberry as part of a game.','vole','market',325,380,'talk',{source:'Wren the gardener',question:'Was this a festival game?',quote:'The moonberry was meant to stay on display. This was not a hiding game.'}),
 ],
 deductions:[
 D('after-close','prints','baker','After closing',['The bakery ran out of flour.','Someone crossed the steps after closing.','The basket was repaired at sunset.'],1,'The steps were clean when Bruna closed; the fresh flour prints appeared afterwards.'),
 D('visitor','prints','milo','A familiar boot',['Milo was beside the basket.','Bruna’s apron broke the basket.','Wren carried the moonberry to market.'],0,'The nicked right-boot print matches the boot only Milo wears. He said he never went inside, which does not rule out visiting the steps.'),
 D('route','basket','trail','Follow the berry',['The berry stayed under the basket.','The berry went to the market.','The berry travelled toward the old mill.'],2,'The continuous berry scent starts at the broken basket and follows the old mill path.'),
 D('care','basket','pantry','Why it was moved',['The berry was moved to keep it safe.','Milo sold it for flour.','The berry fell into the oven.'],0,'The broken slat explains the rolling berry, and Milo’s message explicitly records safekeeping and his plan to return it.'),
 ],
 questions:['What happened?','How did it happen?','Why?'],answers:[['Bruna sold the moonberry.','Milo moved it to the mill pantry.','Wren hid it in the market.'],['The basket broke and the berry rolled free.','The bakery oven exploded.','The clockkeeper swapped the baskets.'],['To win a secret festival game.','To keep it safe while the basket was repaired.','To stop the festival forever.']],solution:[1,0,1],
 ending:'Milo did not enter the closed bakery: he found the moonberry rolling on the steps and tucked it safely into the mill pantry. Dora and Enzo help mend the basket, and the festival gets its centrepiece back.',
},{
 id:'bell',name:'The Silent Festival Bell',intro:'The festival bell stayed silent this morning. Was it the weather, a broken rope, or something the village has overlooked?',
 clues:[
 C('bell','Padded bell','The bell rope is intact. A triangular piece of blue cloth is wrapped around the clapper, stopping it from striking the brass. The cloth has feather embroidery.','bell','market',647,185),
 C('finn','Clockkeeper’s statement','Finn’s blue scarf has feather embroidery and a triangular missing corner that exactly matches the cloth on the bell. He first blames the wind, but says he was tending the roost last night.','owl','market',740,440,'talk',{source:'Finn the clockkeeper',question:'Did you check the bell?',quote:'Perhaps it was the wind. I was looking after the roost last night.',followup:'Yes, the cloth is from my scarf. I padded the clapper for the resting chick. The carer left a note at the roost.'}),
 C('weather','Weather ledger','The mill’s weather ledger records a still night, and the bell rope shows no fraying. There is no evidence of wind damage.','letter','mill',440,525),
 C('cloth-trail','Feather-balm scent','Enzo recognises feather balm on the blue cloth. The same scent trail runs from the bell post to the old mill’s sheltered roost.','scent','market',595,540,'scent',{need:'bell'}),
 C('fibres','Roost fibres','Two blue cloth fibres with the same gold feather stitching are caught on the roost latch. They match the bell padding.','feather','mill',765,455),
 C('rest-note','A request for quiet','A note from the village carer asks Finn to let a rescued chick sleep until morning: “The bell startles it. Please keep the clapper quiet tonight.”','letter','mill',865,170,'look',{need:'keeper'}),
 C('bruna','Evening chime','Bruna heard a clear chime at sunset. The bell and rope were working before everyone went home.','badger','bakery',150,370,'talk',{source:'Bruna the baker',question:'When did the bell last ring?',quote:'It rang clearly at sunset. I heard it as I closed.'}),
 ],
 deductions:[
 D('padding','bell','weather','A deliberate quiet',['The wind snapped the rope.','The clapper was deliberately muffled.','The bell never worked.'],1,'The rope is intact, the night was still, and cloth physically stops the clapper from striking the bell.'),
 D('keeper','bell','finn','The matching scarf',['Bruna wrapped the bell in an apron.','The mill wheel broke the rope.','Finn used a piece of his scarf.'],2,'The feather embroidery and triangular tear match Finn’s missing scarf corner exactly.'),
 D('roost','cloth-trail','fibres','Where the cloth went',['The cloth connects the bell to the mill roost.','The cloth came from the bakery oven.','The fibres prove the wind was strong.'],0,'The feather-balm trail and matching fibres independently connect the bell cloth with the roost latch.'),
 D('kindness','bell','rest-note','The reason for silence',['Finn wanted to cancel the festival.','The bell was quieted so the rescued chick could rest.','The moonberry jammed the rope.'],1,'The request explains why Finn padded the clapper: the rescued chick needed a quiet night.'),
 ],questions:['What happened?','How?','Why?'],answers:[['The wind broke the bell.','Finn deliberately quieted the bell.','Bruna took the bell away.'],['He wrapped the clapper in his scarf cloth.','He cut the rope.','He filled the bell with flour.'],['To sleep through the festival.','To hide a stolen parcel.','To let a rescued chick rest.']],solution:[1,0,2],
 ending:'Finn admits he padded the bell with his scarf to protect the rescued chick’s quiet night. The neighbours move the roost farther from the tower, remove the cloth, and ring a gentle festival chime together.',
},{
 id:'parcel',name:'The Vanishing Seed Parcel',intro:'Wren’s seed parcel never reached the market stall. Reconstruct the delivery before anyone blames the wrong neighbour.',
 clues:[
 C('label','Loose delivery label','A torn delivery label has a patch of dried flour. Its tie is loose, and the ink beneath the fold reads only “…R…”. It was found at the market pickup bench.','letter','market',325,535),
 C('wren','Gardener’s statement','Wren’s seeds were sealed in a blue-ribbon parcel. Bruna’s flour delivery used red twine. The two sat together on the pickup bench before the brief shower.','vole','market',620,395,'talk',{source:'Wren the gardener',question:'How was your parcel packed?',quote:'My seeds had blue ribbon. Bruna’s flour had red twine.',followup:'That gold stitch is mine! Check whether the parcel seal is intact at the bakery.'}),
 C('ribbon','Blue ribbon','A blue ribbon with the gardener’s gold stitch pattern lies beside the bakery flour bin. It matches the ribbon Wren described on the seed parcel.','thread','bakery',425,540),
 C('seed-trail','Seed scent','Enzo follows seed scent into the bakery’s flour bin. The scent comes from the blue-ribbon parcel, not from the flour sacks nearby.','scent','bakery',610,450,'scent',{need:'label'}),
 C('carrier','Carrier’s statement','Milo delivered the parcel marked FLOUR to the bakery. He noticed the label was loosely tied, and says he never opened the sealed parcel.','mouse','mill',285,370,'talk',{source:'Milo the carrier',question:'Where did you take it?',quote:'The label said FLOUR, so I brought it to Bruna. I did not open it.',followup:'The tie was loose when I collected it. Compare the market label with the pickup ledger.'}),
 C('pickup','Pickup ledger','The pickup ledger says both labels fell off during a brief shower. The blue-ribbon parcel and red-twine delivery were relabelled in a hurry, with their labels accidentally swapped.','letter','mill',450,535),
 C('seal','Sealed seed parcel','The bakery’s blue-ribbon parcel is still sealed. Under the folded outer FLOUR label is its original SEEDS label. Its contents have not been removed.','parcel','bakery',390,360,'look',{need:'arrival'}),
 ],deductions:[
 D('delivery','label','carrier','A wrong address',['Milo followed a misplaced label.','Milo opened and sold the seeds.','The seed parcel stayed at the mill.'],0,'The loose, flour-marked label explains Milo’s stated delivery instruction; his account places the parcel at the bakery.'),
 D('arrival','ribbon','wren','The blue ribbon',['Bruna’s flour used blue ribbon.','Wren’s parcel reached the bakery.','The gardener lost an empty basket.'],1,'Wren’s distinctive blue gold-stitched ribbon is at the bakery flour bin.'),
 D('intact','seed-trail','seal','Where the seeds are',['The seeds were planted at night.','The seeds were mixed into bread.','The seeds remain sealed at the bakery.'],2,'The scent identifies the seed parcel, and the unbroken seal confirms the contents are still inside.'),
 D('mixup','label','pickup','The misplaced labels',['The labels were swapped after the shower.','The clockkeeper hid the seeds.','The gardener ordered flour instead.'],0,'The loose tie and flour mark fit the pickup ledger’s explicit account of the two labels being swapped.'),
 ],questions:['Where are the seeds?','What caused it?','What kind of mystery was this?'],answers:[['At the old mill roost.','Sealed in the bakery flour bin.','Sold at the market.'],['The bell rope broke.','Bruna baked the seeds.','The labels were swapped after a shower.'],['An accidental delivery mix-up.','A deliberate theft by Milo.','A secret festival game.']],solution:[1,2,0],
 ending:'The seeds never vanished: a hurried label swap sent the sealed blue-ribbon parcel to the bakery flour bin. Wren gets her seeds back, Bruna gets her flour, and the neighbours use sturdier label ties next time.',
}];
export type Event={t:'select'|'clue'|'deduction'|'wrong'|'hint'|'place'|'hero'|'closed';id?:string};
export class Game{
 caseId:number;place:Place='bakery';who:Who='dora';state:'active'|'closed'='active';paused=false;found:string[]=[];deduced:string[]=[];focus:string|null=null;pair:[string,string]|null=null;mistakes=0;hints=0;events:Event[]=[];speech='';note='Choose a clue marker, then examine it. Talk to the neighbours too.';
 constructor(caseId=0){this.caseId=Math.max(0,Math.min(2,Number.isFinite(caseId)?Math.floor(caseId):0));}
 get case(){return CASES[this.caseId];}get clues(){return this.case.clues.filter(c=>this.found.includes(c.id));}get complete(){return this.case.deductions.every(d=>this.deduced.includes(d.id));}get stars(){return this.state==='closed'?1+Number(this.mistakes===0)+Number(this.hints===0):0;}
 get spots(){return this.case.clues.filter(c=>c.place===this.place);}get selected(){return this.case.clues.find(c=>c.id===this.focus)||null;}
 get required(){return [...new Set(this.case.deductions.flatMap(d=>d.pair))];}
 available(c:Clue){return !c.need||this.found.includes(c.need)||this.deduced.includes(c.need);}
 pause(on:boolean){if(this.state==='active')this.paused=on;}
 move(place:Place){if(this.paused||this.state!=='active'||!Object.hasOwn(PLACES,place))return false;this.place=place;this.focus=null;this.pair=null;this.speech='';this.note=PLACES[place].description;this.events.push({t:'place'});return true;}
 hero(who:Who){if(this.paused||this.state!=='active'||!['dora','enzo'].includes(who))return false;this.who=who;this.events.push({t:'hero'});return true;}
 select(id:string){if(this.paused||this.state!=='active'||!this.spots.some(c=>c.id===id))return false;this.focus=id;this.speech='';this.events.push({t:'select',id});this.note=`${this.selected!.title}: ${this.selected!.kind==='talk'?'ask a question':this.selected!.kind==='scent'?'Enzo can follow this scent':'Dora can examine this closely'}.`;return true;}
 inspect(id=this.focus){if(this.paused||this.state!=='active'||!id)return null;const c=this.spots.find(c=>c.id===id);if(!c)return null;if(!this.available(c)){this.note='This needs more context. Compare the evidence you already have, then return.';return null;}if(c.kind==='look'&&this.who!=='dora'||c.kind==='scent'&&this.who!=='enzo'){this.note=c.kind==='look'?'Let Dora take a closer look.':'Enzo can follow the scent.';return null;}if(c.kind==='talk'){this.note='Choose a question for this neighbour.';return null;}return this.collect(c);}
 private collect(c:Clue){if(!this.found.includes(c.id)){this.found.push(c.id);this.events.push({t:'clue',id:c.id});}this.note=`Added to the notebook: ${c.title}.`;return c;}
 ask(id:string,follow=false){if(this.paused||this.state!=='active')return null;const c=this.spots.find(c=>c.id===id&&c.kind==='talk');if(!c||!this.available(c))return null;this.focus=c.id;if(follow){if(!c.followup||!this.found.includes(c.id)||!this.case.deductions.some(d=>this.deduced.includes(d.id)&&d.pair.includes(c.id)))return null;this.speech=c.followup;this.note=c.followup;this.events.push({t:'select',id});return c;}this.speech=c.quote||c.description;return this.collect(c);}
 choosePair(a:string,b:string){if(this.paused||this.state!=='active'||a===b||!this.found.includes(a)||!this.found.includes(b))return false;this.pair=[a,b];const known=this.inference;this.note=known&&this.deduced.includes(known.id)?known.reason:'Read both clues, then choose what they establish.';return true;}
 get inference(){return this.pair?this.case.deductions.find(d=>d.pair.every(id=>this.pair!.includes(id)))||null:null;}
 connect(choice:number){if(this.paused||this.state!=='active'||!Number.isInteger(choice)||choice<0||choice>2)return false;const d=this.inference;if(!d){this.note='These clues do not establish a useful link yet. Try a pair about time, identity, route or reason.';return false;}if(this.deduced.includes(d.id)){this.note=d.reason;return choice===d.answer;}if(choice!==d.answer){this.mistakes++;this.events.push({t:'wrong'});this.note='That conclusion goes further than this evidence. Read both clues again.';return false;}if(!this.deduced.includes(d.id)){this.deduced.push(d.id);this.events.push({t:'deduction',id:d.id});}this.note=d.reason;return true;}
 hint(){if(this.paused||this.state!=='active')return '';this.hints++;this.events.push({t:'hint'});const c=this.case.clues.find(c=>this.required.includes(c.id)&&!this.found.includes(c.id)&&this.available(c));if(c){this.note=`Visit ${PLACES[c.place].name}. ${c.kind==='scent'?'Enzo should follow':c.kind==='talk'?'Ask a neighbour about':'Dora should examine'} ${c.title.toLowerCase()}.`;return this.note;}const d=this.case.deductions.find(d=>!this.deduced.includes(d.id)&&d.pair.every(id=>this.found.includes(id)));this.note=d?`Compare “${this.case.clues.find(c=>c.id===d.pair[0])!.title}” with “${this.case.clues.find(c=>c.id===d.pair[1])!.title}”. What can both prove?`:'Your deductions are ready. Explain the whole case.';return this.note;}
 explain(answers:number[]){if(this.paused||this.state!=='active'||!this.complete||answers.length!==3||answers.some(n=>!Number.isInteger(n)||n<0||n>2))return false;if(!answers.every((a,i)=>a===this.case.solution[i])){this.mistakes++;this.events.push({t:'wrong'});this.note='The explanation does not fit all four deductions. Check each part against the notebook.';return false;}this.state='closed';this.pair=null;this.speech='';this.note=this.case.ending;this.events.push({t:'closed'});return true;}
 save(){return JSON.stringify({v:1,caseId:this.caseId,place:this.place,who:this.who,state:this.state,found:this.found,deduced:this.deduced,focus:this.focus,pair:this.pair,mistakes:this.mistakes,hints:this.hints});}
 static load(text:string):Game|null{try{const s=JSON.parse(text);if(s.v!==1||!Number.isInteger(s.caseId)||s.caseId<0||s.caseId>=CASES.length||s.state!=='active'||!Object.hasOwn(PLACES,s.place)||!['dora','enzo'].includes(s.who)||!Number.isSafeInteger(s.mistakes)||s.mistakes<0||s.mistakes>10000||!Number.isSafeInteger(s.hints)||s.hints<0||s.hints>10000)return null;const g=new Game(s.caseId);if(!Array.isArray(s.found)||!Array.isArray(s.deduced)||new Set(s.found).size!==s.found.length||new Set(s.deduced).size!==s.deduced.length||s.found.some((id:string)=>!g.case.clues.some(c=>c.id===id))||s.deduced.some((id:string)=>!g.case.deductions.some(d=>d.id===id&&d.pair.every(p=>s.found.includes(p)))))return null;
  if(s.found.some((id:string)=>{const c=g.case.clues.find(c=>c.id===id)!;return c.need&&!s.found.includes(c.need)&&!s.deduced.includes(c.need);})||s.focus!==null&&!g.case.clues.some(c=>c.id===s.focus&&c.place===s.place)||s.pair!==null&&(!Array.isArray(s.pair)||s.pair.length!==2||s.pair[0]===s.pair[1]||s.pair.some((id:string)=>!s.found.includes(id))))return null;
  g.place=s.place;g.who=s.who;g.found=s.found;g.deduced=s.deduced;g.focus=s.focus;g.pair=s.pair;g.mistakes=s.mistakes;g.hints=s.hints;g.paused=true;g.note='Your notebook is restored. Carry on when ready.';return g;
 }catch{return null;}}
}
