import * as T from 'three';
import {createChinchilla} from './chinchilla';
import {EscapeGame,BLOCKS,HIDES} from './escape-game';
export class EscapeScene{
 scene=new T.Scene();camera=new T.OrthographicCamera(-12,12,12,-12,.1,150);renderer:T.WebGLRenderer;cage=new T.Group();room=new T.Group();heroes=[createChinchilla(false),createChinchilla(true)];guards:T.Group[]=[];cones:T.Mesh[]=[];marker:T.Mesh;dust:T.Mesh;door=new T.Group();phase='';
 constructor(public canvas:HTMLCanvasElement){this.renderer=new T.WebGLRenderer({canvas,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.toneMapping=T.ACESFilmicToneMapping;this.scene.background=new T.Color('#17212b');this.scene.add(new T.HemisphereLight(0xa5bbd1,0x514136,2.2));const light=new T.DirectionalLight(0xffd5a0,2.7);light.position.set(-4,15,7);this.scene.add(light);this.scene.add(this.cage,this.room);
 const wood=0x9f7b51,metal=0x9eabb2;this.box(this.cage,0,-.18,0,10,.35,8,wood);this.box(this.cage,0,2,-4,10,4.4,.16,wood);for(const x of [-5,5])this.box(this.cage,x,2,0,.16,4.4,8,wood);this.box(this.cage,0,2.3,-2.8,9.8,.18,2.2,0xbd9c6b);this.box(this.cage,-3,1.15,-2,2,.15,1.4,wood);
 // Front frame and mesh echo the photographed silver wire door.
 for(const x of [-5,5])this.box(this.cage,x,2,4,.16,4.4,.16,metal);for(const y of [0,4.2])this.box(this.cage,0,y,4,10,.14,.16,metal);
 const wire=new T.LineBasicMaterial({color:0xbbc9d2,transparent:true,opacity:.23});const pts:T.Vector3[]=[];for(let x=-4.8;x<5;x+=.55)pts.push(new T.Vector3(x,0,4),new T.Vector3(x,4.2,4));for(let y=.3;y<4.2;y+=.45)pts.push(new T.Vector3(-5,y,4),new T.Vector3(5,y,4));this.door.add(new T.LineSegments(new T.BufferGeometry().setFromPoints(pts),wire));this.cage.add(this.door);this.box(this.cage,0,.8,3.9,.35,.55,.22,0xd1b979);
 const tunnel=new T.Mesh(new T.CylinderGeometry(.75,.75,2.5,24,1,true),new T.MeshStandardMaterial({color:0x137bbc,metalness:.65,roughness:.3,side:T.DoubleSide}));tunnel.rotation.z=Math.PI/2;tunnel.position.set(-3,.77,0);this.cage.add(tunnel);for(const x of [-4.25,-1.75]){const ring=new T.Mesh(new T.TorusGeometry(.75,.06,6,24),new T.MeshStandardMaterial({color:0x82b3ce,metalness:.6}));ring.rotation.y=Math.PI/2;ring.position.set(x,.77,0);this.cage.add(ring)}
 for(const x of [2,3.6])this.box(this.cage,x,.65,-1,.14,1.3,1.8,0xc58e9e);this.box(this.cage,2.8,1.3,-1,1.8,.14,1.8,0xe5afbf);this.box(this.cage,2.8,.65,-1.9,1.8,1.3,.1,0xc58e9e);
 const bottle=new T.Mesh(new T.CylinderGeometry(.35,.35,2,18),new T.MeshStandardMaterial({color:0xc6d4d5,transparent:true,opacity:.48,roughness:.2}));bottle.position.set(4.3,1.9,3.5);this.cage.add(bottle);this.box(this.cage,4.3,3,3.5,.8,.28,.8,0x269dc9);this.box(this.cage,4.3,.75,3.3,.13,.6,.13,metal);
 for(const x of [-1.6,1.1]){this.box(this.cage,x,3.1,3.5,1.8,.85,.5,0xb7bbb9);for(const dx of [-.55,.55])this.box(this.cage,x+dx,2.8,3.82,.18,.18,.14,metal)}
 this.box(this.cage,3,.12,-2.8,2.5,.2,1.1,0xc2b899);for(let i=0;i<35;i++)this.box(this.cage,2+(i%7)*.3,.26,-3.1+Math.floor(i/7)*.13,.38,.02,.04,0xb39d65,(i%4)*.5);
 // Wooden room, shelving, covered hiding places, and a green exit.
 this.box(this.room,0,-.2,0,25,.3,19,0x795337);for(let x=-12;x<12;x+=1.5)for(let z=-9;z<9;z+=1.5)this.box(this.room,x+.7,-.03,z+.7,1.46,.04,1.46,(Math.round((x+z)*2)%3)?0x8b603f:0x9b6f47);
 this.box(this.room,0,1.6,-9,25,3.5,.2,0x766b61);this.box(this.room,-12,1.6,0,.2,3.5,18,0x766b61);
 for(const b of BLOCKS){this.box(this.room,b.x,1,b.z,b.w,2,b.d,0x62594e);for(const y of [.3,1.2])this.box(this.room,b.x,y,b.z+b.d/2+.02,b.w-.2,.08,.04,0xa9987a)}
 for(const h of HIDES){const top=this.box(this.room,h.x,1.6,h.z,h.w,.12,h.d,0x73828b);(top.material as T.MeshStandardMaterial).transparent=true;(top.material as T.MeshStandardMaterial).opacity=.4;for(const dx of [-h.w/2+.12,h.w/2-.12])for(const dz of [-h.d/2+.12,h.d/2-.12])this.box(this.room,h.x+dx,.8,h.z+dz,.12,1.6,.12,0x59646a);this.box(this.room,h.x,.005,h.z,h.w,.015,h.d,0x314d5c)}
 this.box(this.room,-1,.6,-6,2,.2,1.2,0x96856e);this.box(this.room,-1,.75,-6,.45,.05,.3,0xc9e3c1);this.box(this.room,10.8,1.5,-8.8,2.4,3,.15,0x355c50);
 const exitLight=new T.PointLight(0x8be3af,12,6);exitLight.position.set(10,2,-7);this.room.add(exitLight);
 const textureCanvas=document.createElement('canvas');textureCanvas.width=128;textureCanvas.height=64;const c=textureCanvas.getContext('2d')!;c.fillStyle='#203440';c.fillRect(0,0,128,64);c.fillStyle='#eef1e7';c.font='bold 40px Arial';c.textAlign='center';c.fillText('ICE',64,47);const tag=new T.CanvasTexture(textureCanvas);
 for(let i=0;i<2;i++){const guard=new T.Group();for(const x of [-.2,.2])this.box(guard,x,.6,0,.25,1.2,.3,0x1f2e3d);this.box(guard,0,1.5,0,.85,.9,.42,0x2e4356);const head=new T.Mesh(new T.SphereGeometry(.26,12,8),new T.MeshStandardMaterial({color:0xa18b77}));head.position.y=2.2;guard.add(head);this.box(guard,0,2.4,.06,.65,.12,.55,0x233443);const label=new T.Mesh(new T.PlaneGeometry(.65,.33),new T.MeshBasicMaterial({map:tag}));label.position.set(0,1.65,.22);guard.add(label);this.box(guard,.55,1.3,.25,.15,.15,.4,0xcaccc0);this.guards.push(guard);this.room.add(guard);
 const shape=new T.Shape();shape.moveTo(0,0);for(let j=0;j<=24;j++){const a=-Math.PI/5+j/24*Math.PI*2/5;shape.lineTo(Math.sin(a)*5.6,Math.cos(a)*5.6)}shape.closePath();const cone=new T.Mesh(new T.ShapeGeometry(shape),new T.MeshBasicMaterial({color:0xf3d990,transparent:true,opacity:.13,side:T.DoubleSide,depthWrite:false}));cone.rotation.x=Math.PI/2;this.room.add(cone);this.cones.push(cone)}
 this.heroes.forEach(h=>{h.root.scale.setScalar(.55);h.fur.forEach(f=>f.geometry.setDrawRange(0,Math.floor(f.geometry.getAttribute('position').count/24)*4));this.scene.add(h.root)});
 this.marker=new T.Mesh(new T.TorusGeometry(.6,.055,6,32),new T.MeshBasicMaterial({color:0xe8c782,transparent:true,opacity:.9}));this.marker.rotation.x=Math.PI/2;this.scene.add(this.marker);this.dust=new T.Mesh(new T.SphereGeometry(.7,12,8),new T.MeshBasicMaterial({color:0xc7bbd5,transparent:true,opacity:.35,depthWrite:false}));this.scene.add(this.dust);this.resize('cage')}
 box(parent:T.Object3D,x:number,y:number,z:number,w:number,h:number,d:number,color:number,angle=0){const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color,roughness:.8}));m.position.set(x,y,z);m.rotation.y=angle;parent.add(m);return m}
 resize(phase=this.phase||'cage'){const w=this.canvas.clientWidth,h=this.canvas.clientHeight,aspect=w/h,height=Math.max(phase==='cage'?14:25,(phase==='cage'?15:31)/aspect);this.renderer.setSize(w,h,false);this.camera.left=-height*aspect/2;this.camera.right=height*aspect/2;this.camera.top=height/2;this.camera.bottom=-height/2;this.camera.updateProjectionMatrix()}
 render(g:EscapeGame,t:number){if(this.phase!==g.phase){this.phase=g.phase;this.resize();this.room.visible=g.phase==='room';this.cage.scale.setScalar(g.phase==='cage'?1:.4);this.cage.position.set(g.phase==='cage'?0:-9,0,g.phase==='cage'?0:-7);this.camera.position.set(g.phase==='cage'?11:16,g.phase==='cage'?15:26,g.phase==='cage'?15:20);this.camera.lookAt(0,g.phase==='cage'?1:0,0)}
 this.heroes.forEach((h,i)=>{h.root.position.set(g.x+(i?.32:-.32),g.y,g.z+(i?.15:-.15));h.root.rotation.y=Math.atan2(-g.face.z,g.face.x);h.root.scale.set(.55,g.sneaking?.4:.55,.55);h.body.position.y=g.moving?Math.sin(t*13)*.025:0;h.ears.forEach((e,j)=>e.rotation.x=Math.sin(t*2+j)*.06)});
 this.guards.forEach((m,i)=>{const guard=g.guards[i];m.position.set(guard.x,0,guard.z);m.rotation.y=guard.angle;const cone=this.cones[i];cone.position.set(guard.x,.06,guard.z);cone.rotation.set(Math.PI/2,0,-guard.angle);const mat=cone.material as T.MeshBasicMaterial;mat.color.set(g.noticed?0xeb8d70:0xf3d990)});
 this.marker.position.set(g.target.x,.12,g.target.z);this.marker.scale.setScalar(.95+Math.sin(t*3)*.08);this.marker.visible=g.state!=='won';this.dust.visible=!!g.decoy;if(g.decoy){this.dust.position.set(g.decoy.x,.5,g.decoy.z);this.dust.scale.setScalar(1+(3.5-g.decoyTime)*.6)}this.renderer.render(this.scene,this.camera)}
 dispose(){const geo=new Set<T.BufferGeometry>(),mat=new Set<T.Material>(),textures=new Set<T.Texture>();this.scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.LineSegments){geo.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){mat.add(m);if('map'in m&&m.map instanceof T.Texture)textures.add(m.map)}}});textures.forEach(t=>t.dispose());geo.forEach(g=>g.dispose());mat.forEach(m=>m.dispose());this.renderer.dispose()}
}
