import {Game,WIDTH,HEIGHT,BUMPERS,TARGETS,BURROWS,FLIPPERS,LAUNCH,type Ev} from './pinball-game';
type C=CanvasRenderingContext2D;type Sprite={image:HTMLImageElement;x:number;y:number;w:number;h:number};
const sprites=new Map<string,Sprite>();let table:HTMLImageElement|null=null,promise:Promise<void>|null=null;
export function loadArt(){if(promise)return promise;promise=Promise.all(['table','pieces'].map(name=>new Promise<HTMLImageElement>((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error(`Cannot load ${name}`));im.src=`/art/pinball/${name}.png`;}))).then(([t,p])=>{table=t;const cv=document.createElement('canvas');cv.width=p.width;cv.height=p.height;const c=cv.getContext('2d')!;c.drawImage(p,0,0);const px=c.getImageData(0,0,p.width,p.height).data;
 const regions:[string,number,number,number,number][]=[['bumper',0,0,510,515],['flipper',520,150,675,285],['gold',1220,120,316,390],['moon',0,545,420,479],['dora',420,515,550,509],['enzo',980,515,556,509]];
 for(const [key,x0,y0,w,h] of regions){let x=w,y=h,r=0,b=0;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++)if(px[((y0+yy)*p.width+x0+xx)*4+3]>24){x=Math.min(x,xx);y=Math.min(y,yy);r=Math.max(r,xx);b=Math.max(b,yy);}if(r>x&&b>y)sprites.set(key,{image:p,x:x0+x,y:y0+y,w:r-x+1,h:b-y+1});}if(sprites.size<6)throw new Error('Incomplete pinball artwork');
 }).catch(e=>{promise=null;throw e;});return promise;}
function sprite(c:C,key:string,x:number,y:number,w:number,h:number){const s=sprites.get(key);if(!s)return;const k=Math.min(w/s.w,h/s.h);c.drawImage(s.image,s.x,s.y,s.w,s.h,x+(w-s.w*k)/2,y+h-s.h*k,s.w*k,s.h*k);}
function glow(c:C,x:number,y:number,r:number,color:string){const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'rgba(255,215,110,0)');c.fillStyle=g;c.fillRect(x-r,y-r,r*2,r*2);}
function text(c:C,t:string,x:number,y:number,size=16,color='#ffedb9'){c.font=`600 ${size}px Georgia,serif`;c.textAlign='center';c.textBaseline='middle';c.fillStyle=color;c.fillText(t,x,y);}
export function graphic(c:C,key:'moon'|'burrow',w:number,h:number){c.clearRect(0,0,w,h);if(key==='burrow'&&table)c.drawImage(table,table.width*.13,table.height*.025,table.width*.25,table.height*.23,0,0,w,h);else sprite(c,key,0,0,w,h);}
export function portrait(c:C,who:'dora'|'enzo',w:number,h:number){c.clearRect(0,0,w,h);sprite(c,who,0,0,w,h);}
export class Stage{
 motion=typeof window==='undefined'||!matchMedia('(prefers-reduced-motion: reduce)').matches;clock=0;effects:(Ev&{born:number})[]=[];private tails=new Map<number,{x:number;y:number}[]>();
 feed(events:Ev[]){if(this.motion)this.effects.push(...events.map(e=>({...e,born:this.clock})));this.effects=this.effects.slice(-60);}
 update(dt:number,g:Game){if(!this.motion){this.effects=[];this.tails.clear();return;}if(g.paused||g.state==='over')return;this.clock+=Math.min(.1,dt);this.effects=this.effects.filter(e=>this.clock-e.born<.8);const ids=new Set(g.balls.map(b=>b.id));for(const id of this.tails.keys())if(!ids.has(id))this.tails.delete(id);for(const b of g.balls){const t=this.tails.get(b.id)||[];t.push({x:b.x,y:b.y});if(t.length>10)t.shift();this.tails.set(b.id,t);}}
 inspect(){return{clock:this.clock,motion:this.motion,trails:this.tails.size,effects:this.effects.length};}
 draw(c:C,w:number,h:number,dpr:number,g:Game){c.setTransform(dpr*w/WIDTH,0,0,dpr*h/HEIGHT,0,0);c.clearRect(0,0,WIDTH,HEIGHT);if(!table||sprites.size<6)return;c.drawImage(table,0,0,WIDTH,HEIGHT);
  for(const p of BUMPERS){const hit=this.effects.findLast(e=>e.t==='bumper'&&Math.hypot(e.x-p.x,e.y-p.y)<3),age=hit?this.clock-hit.born:1;glow(c,p.x,p.y,70,age<.45?`rgba(255,224,124,${(.45-age)*.8})`:'rgba(255,218,114,.09)');const bounce=this.motion&&age<.3?Math.sin(age/.3*Math.PI)*4:0;sprite(c,'bumper',p.x-54-bounce,p.y-62-bounce,108+bounce*2,114+bounce*2);}
  // Each brass stud on the stone wall lights the burrow window above it.
  const lamp=(p:{x:number;y:number},r:number,lit:boolean)=>{const grad=c.createRadialGradient(p.x-r*.3,p.y-r*.3,1,p.x,p.y,r+1);grad.addColorStop(0,lit?'#fff5c7':'#5d4224');grad.addColorStop(.6,lit?'#efb437':'#2b1a0c');grad.addColorStop(1,'#8e622f');c.fillStyle=grad;c.beginPath();c.arc(p.x,p.y,r,0,Math.PI*2);c.fill();if(lit)glow(c,p.x,p.y,r*1.7,'rgba(255,207,85,.28)');};
  BURROWS.forEach((p,i)=>lamp(p,17,g.lamps[i]));TARGETS.forEach((p,i)=>{lamp(p,p.r,g.lamps[i]);c.strokeStyle='#e9c77c';c.lineWidth=1.5;c.beginPath();c.arc(p.x,p.y,p.r-.75,0,Math.PI*2);c.stroke();});
  for(let i=0;i<2;i++){const f=FLIPPERS[i],s=sprites.get('flipper')!;c.save();c.translate(f.x,f.y);c.rotate(g.angles[i]);const sourceAngle=Math.atan2(55,485),k=f.length/Math.hypot(485,55);c.rotate(-sourceAngle);c.scale(k,k);c.shadowColor='#110b08aa';c.shadowBlur=15;c.shadowOffsetY=15;c.drawImage(s.image,s.x,s.y,s.w,s.h,s.x-630,s.y-250,s.w,s.h);c.restore();}
  if(g.state==='ready'){sprite(c,'gold',LAUNCH.x-15,LAUNCH.y-18+g.charge*6,30,33);c.fillStyle='#ffd98e';c.fillRect(915,955,20,3+g.charge*26);}
  for(const b of g.balls){const trail=this.tails.get(b.id)||[];if(this.motion&&trail.length>1){c.save();c.lineWidth=3;c.lineCap='round';for(let i=1;i<trail.length;i++){c.strokeStyle=b.moon?`rgba(213,147,255,${i/trail.length*.35})`:`rgba(255,212,116,${i/trail.length*.45})`;c.beginPath();c.moveTo(trail[i-1].x,trail[i-1].y);c.lineTo(trail[i].x,trail[i].y);c.stroke();}c.restore();}glow(c,b.x,b.y,24,b.moon?'rgba(201,139,255,.2)':'rgba(255,217,117,.2)');sprite(c,b.moon?'moon':'gold',b.x-15,b.y-18,30,33);}
  for(const e of this.effects){const a=this.clock-e.born;c.save();c.globalAlpha=Math.max(0,1-a/.8);if(e.n&&['bumper','sling','target','ramp','rescue'].includes(e.t))text(c,`+${e.n.toLocaleString()}`,e.x,e.y-25-a*30,e.t==='rescue'?24:16);if(['bumper','rescue','multiball'].includes(e.t)){for(let i=0;i<9;i++){const angle=i*Math.PI*2/9,r=20+a*50;text(c,'✧',e.x+Math.cos(angle)*r,e.y+Math.sin(angle)*r*.65,11);}}if(e.t==='dust'||e.t==='lock'){for(let i=0;i<15;i++){c.fillStyle='#e6d7b6';c.beginPath();c.ellipse(767+Math.cos(i*2.4)*a*(15+i),175+Math.sin(i*2.4)*a*(8+i),1.7,1.1,0,0,Math.PI*2);c.fill();}}c.restore();}
  if(g.multiball)text(c,'MOONBERRY MULTIBALL · DOUBLE POINTS',500,575,22,'#e6c0ff');else if(g.combo>1&&g.comboUntil>g.time)text(c,`${g.combo}× BUMPER COMBO`,500,585,20);
  if(g.time<g.saveUntil&&g.state==='play')text(c,`BALL SAVE ${Math.ceil(g.saveUntil-g.time)}s`,500,920,16);
  if(g.time<g.tiltUntil)text(c,`TILT · ${Math.ceil(g.tiltUntil-g.time)}s`,500,600,25,'#ffc1a4');
 }
}
