import * as T from 'three';
import {createChinchilla,animateChinchilla} from './chinchilla';
import {PitGame,ORBS} from './pit-game';
export class PitScene{
 scene=new T.Scene();camera=new T.OrthographicCamera(-9,9,13,-13,.1,80);renderer:T.WebGLRenderer;heroes=[createChinchilla(true),createChinchilla(false)];ballShapes={orb:new T.SphereGeometry(.17,10,8),drill:new T.ConeGeometry(.15,.48,7),scatter:new T.IcosahedronGeometry(.19,0),gale:new T.TorusGeometry(.17,.055,6,14)};ballPool:T.Mesh[]=[];brickPool:T.Group[]=[];fxPool:T.Mesh[]=[];line:T.Line;ray=new T.Raycaster();plane=new T.Plane(new T.Vector3(0,1,0),0);
 constructor(public canvas:HTMLCanvasElement){this.renderer=new T.WebGLRenderer({canvas,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.scene.background=new T.Color('#151a24');this.scene.add(new T.HemisphereLight(0xc9e8ed,0x4e3740,2.4));const key=new T.DirectionalLight(0xffe0b4,3);key.position.set(-5,15,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-12,right:12,top:16,bottom:-16});this.scene.add(key);
 this.box(0,-.35,-1,12.5,.5,23,0x323743);for(let x=-5.25;x<6;x+=1.5)for(let z=-10.5;z<10;z+=1.5)this.box(x,-.07,z,1.47,.09,1.47,(Math.round(x+z)%3)?0x394452:0x414959);
 for(const x of [-6.2,6.2]){this.box(x,.3,-1,.38,1,23,0x786458);this.box(x,.85,-1,.10,.06,23,0xc7a476)}this.box(0,.3,-11.5,12.6,1,.35,0x786458);this.box(0,.015,5.1,12,.02,.08,0xe58e7b);this.box(0,.01,8,11.8,.04,4,0x4d3c50);
 this.heroes.forEach(h=>{this.scene.add(h.root);h.root.scale.setScalar(.9);h.fur.forEach(f=>f.geometry.setDrawRange(0,Math.floor(f.geometry.getAttribute('position').count/8)*4))});
 const ballGeo=this.ballShapes.orb;for(let i=0;i<180;i++){const m=new T.Mesh(ballGeo,new T.MeshStandardMaterial({color:0xffd787,emissive:0xffd787,emissiveIntensity:.5,roughness:.35}));this.scene.add(m);this.ballPool.push(m)}
 for(let i=0;i<80;i++){const g=new T.Group();const body=new T.Mesh(new T.BoxGeometry(1.23,.75,.99),new T.MeshStandardMaterial({color:0x9a7665,roughness:.65}));body.position.y=.43;body.castShadow=true;g.add(body);for(const x of [-.27,.27]){const eye=new T.Mesh(new T.SphereGeometry(.07,8,6),new T.MeshBasicMaterial({color:0xf4d6a0}));eye.position.set(x,.72,.52);g.add(eye)}this.scene.add(g);this.brickPool.push(g)}
 for(let i=0;i<100;i++){const m=new T.Mesh(new T.TorusGeometry(1,.026,5,24),new T.MeshBasicMaterial({transparent:true,depthWrite:false}));m.rotation.x=Math.PI/2;this.scene.add(m);this.fxPool.push(m)}this.line=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]),new T.LineDashedMaterial({color:0xe9d6ab,dashSize:.25,gapSize:.2,transparent:true,opacity:.45}));this.scene.add(this.line);this.camera.position.set(0,23,13);this.camera.lookAt(0,0,-1);this.resize()}
 box(x:number,y:number,z:number,w:number,h:number,d:number,color:number){const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color,roughness:.9}));m.position.set(x,y,z);m.receiveShadow=true;this.scene.add(m)}
 resize(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;this.renderer.setSize(w,h,false);const aspect=w/h,height=Math.max(23,14/aspect);this.camera.top=height/2;this.camera.bottom=-height/2;this.camera.left=-height*aspect/2;this.camera.right=height*aspect/2;this.camera.updateProjectionMatrix()}
 pick(x:number,y:number){const r=this.canvas.getBoundingClientRect();this.ray.setFromCamera(new T.Vector2((x-r.left)/r.width*2-1,1-(y-r.top)/r.height*2),this.camera);const p=this.ray.ray.intersectPlane(this.plane,new T.Vector3());return p?{x:Math.max(-6,Math.min(6,p.x)),z:p.z}:null}
 project(x:number,z:number,y=1){const p=new T.Vector3(x,y,z).project(this.camera);return {x:(p.x+1)*50,y:(1-p.y)*50}}
 render(g:PitGame,t:number){this.heroes.forEach((h,i)=>{h.root.position.set(g.x+(i? .78:-.78),.05,g.z);animateChinchilla(h,g.playing?g.time:t,0,true,1);h.root.rotation.y=Math.atan2(g.z-g.aim.z,g.aim.x-h.root.position.x);h.body.rotation.z=Math.sin(g.fireTime*14)*.04});this.ballPool.forEach((m,i)=>{const b=g.balls[i];m.visible=!!b;if(b){m.position.set(b.x,.5,b.z);m.geometry=b.kind==='drill'?this.ballShapes.drill:b.kind==='scatter'||b.kind==='shrapnel'?this.ballShapes.scatter:b.kind==='gale'||b.kind==='moonwhirl'?this.ballShapes.gale:this.ballShapes.orb;m.scale.setScalar(b.fragment?.65:b.kind==='meteor'||b.kind==='moonwhirl'?1.5:1);if(b.kind==='drill')m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),new T.Vector3(b.vx,0,b.vz).normalize());else m.rotation.set(Math.PI/2,0,t*4);const mat=m.material as T.MeshStandardMaterial;mat.color.set(ORBS[b.kind].color);mat.emissive.copy(mat.color)}});const living=g.alive;this.brickPool.forEach((root,i)=>{const e=living[i];root.visible=!!e;if(e){root.position.set(e.x,.02,e.z);root.scale.set(e.boss?2.4:1,e.boss?1.5:1,e.boss?1.6:1);const mat=(root.children[0] as T.Mesh).material as T.MeshStandardMaterial;mat.color.set(e.slow>0?0x8fcedd:e.poison>0?0x8faf66:e.burn>0?0xcc815c:e.boss?0x9a70b4:0x9a7865);mat.emissive.set(e.flash>0?0x80653b:0x000000)}});this.fxPool.forEach((m,i)=>{const e=g.effects[i];m.visible=!!e;if(e){m.position.set(e.x,.24,e.z);m.scale.setScalar(e.radius*(.2+e.age/e.life));const mat=m.material as T.MeshBasicMaterial;mat.color.set(e.color);mat.opacity=1-e.age/e.life}});const a=new T.Vector3(g.x,.15,g.z-.6),dir=new T.Vector3(g.aim.x-g.x,0,Math.min(-1.5,g.aim.z-g.z)).normalize();const pos=this.line.geometry.getAttribute('position') as T.BufferAttribute;pos.setXYZ(0,a.x,a.y,a.z);a.addScaledVector(dir,4);pos.setXYZ(1,a.x,a.y,a.z);pos.needsUpdate=true;this.line.computeLineDistances();this.line.visible=g.playing&&!g.lost;this.renderer.render(this.scene,this.camera)}
 dispose(){const geo=new Set<T.BufferGeometry>(),mat=new Set<T.Material>();this.scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line){geo.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])mat.add(m)}});Object.values(this.ballShapes).forEach(g=>geo.add(g));geo.forEach(g=>g.dispose());mat.forEach(m=>m.dispose());this.renderer.dispose()}
}
