import {random} from './dungeon.js';
export type OrbKind='seed'|'stone'|'frost'|'ember'|'spark'|'spore'|'meteor'|'steam'|'tempest';
export const ORBS:Record<OrbKind,{name:string;color:string;description:string}>={
 seed:{name:'Seedshot',color:'#e9c879',description:'Quick, reliable ricochets.'},stone:{name:'Riverstone',color:'#c4b7e9',description:'Heavy hits for 60% more damage.'},
 frost:{name:'Snowpea',color:'#8cdef1',description:'Slows enemy advance by 60% for 3 seconds.'},ember:{name:'Embernut',color:'#f99c70',description:'Burns for 4 damage per second for 3 seconds.'},
 spark:{name:'Static Puff',color:'#efed9a',description:'Arcs to the nearest enemy within 3 steps.'},spore:{name:'Sporeball',color:'#a6db97',description:'Poisons for 3 damage per second for 5 seconds.'},
 meteor:{name:'Acorn Meteor',color:'#e8adff',description:'Heavy exploding ricochets damage nearby enemies.'},steam:{name:'Steam Bloom',color:'#c5edec',description:'Explodes in scalding frost: slows and burns groups.'},tempest:{name:'Spore Tempest',color:'#bded67',description:'Poisoned lightning jumps through three enemies.'}
};
export const RECIPES:{a:OrbKind;b:OrbKind;result:OrbKind}[]=[{a:'seed',b:'stone',result:'meteor'},{a:'frost',b:'ember',result:'steam'},{a:'spark',b:'spore',result:'tempest'}];
export type Brick={id:number;x:number;z:number;hp:number;maxHp:number;boss:boolean;slow:number;burn:number;poison:number;flash:number};
export type Ball={id:number;x:number;z:number;vx:number;vz:number;kind:OrbKind;damage:number;life:number;last:number;lock:number;returns:number};
export type Upgrade={id:string;name:string;description:string;color:string};
export type PitEffect={id:number;x:number;z:number;age:number;life:number;color:string;radius:number;value?:number};
export class PitGame{
 roll:()=>number;playing=false;paused=false;lost=false;won=false;choice:Upgrade[]=[];x=0;z=7.7;aim={x:0,z:-6};hp=100;maxHp=100;level=1;xp=0;depth=1;wave=0;nextWave=0;time=0;fireTime=0;auto=true;fireHeld=false;shot=0;serial=0;charge=0;kills=0;combo=0;bestCombo=0;comboTime=0;score=0;power=1;rate=1;extra=0;hurt=0;message='';messageTime=0;orbs:{kind:OrbKind;rank:number}[]=[{kind:'seed',rank:1},{kind:'stone',rank:1}];enemies:Brick[]=[];balls:Ball[]=[];effects:PitEffect[]=[];events:string[]=[];
 constructor(seed=Math.floor(Math.random()*4294967296)){this.roll=random(seed);this.spawnWave()}
 get xpNext(){return 35+(this.level-1)*22}
 get alive(){return this.enemies.filter(e=>e.hp>0)}
 get active(){return this.playing&&!this.paused&&!this.lost&&!this.won&&!this.choice.length}
 say(s:string){this.message=s;this.messageTime=3}
 effect(x:number,z:number,color:string,radius:number,value?:number){this.effects.push({id:this.serial++,x,z,color,radius,value,age:0,life:value?.65:.4})}
 spawnWave(){this.wave++;this.nextWave=7;if(this.wave===12){this.enemies.push({id:this.serial++,x:0,z:-10,hp:500*this.depth,maxHp:500*this.depth,boss:true,slow:0,burn:0,poison:0,flash:0});this.say('The Great Dustbreaker descends.');return}const cols=[-4.5,-3,-1.5,0,1.5,3,4.5];for(let i=cols.length-1;i>0;i--){const j=Math.floor(this.roll()*(i+1));[cols[i],cols[j]]=[cols[j],cols[i]]}for(const x of cols.slice(0,3+Math.floor(this.roll()*3))){const hp=Math.round((19+this.wave*4+Math.floor(this.roll()*12))*(1+(this.depth-1)*.45));this.enemies.push({id:this.serial++,x,z:-10,hp,maxHp:hp,boss:false,slow:0,burn:0,poison:0,flash:0})}this.events.push('wave')}
 hit(e:Brick,damage:number,combo=true){if(e.hp<=0)return;e.hp=Math.max(0,e.hp-damage);e.flash=.12;if(combo){this.combo++;this.comboTime=1.3;this.bestCombo=Math.max(this.bestCombo,this.combo);this.effect(e.x,e.z,'#f8de9a',.5,Math.round(damage));}if(e.hp===0){this.kills++;this.score+=Math.round(e.maxHp)*(1+Math.min(this.combo,30)/10);this.charge=Math.min(100,this.charge+8);this.xp+=e.boss?70:12;this.effect(e.x,e.z,e.boss?'#ddb3ff':'#aadfbe',e.boss?2:1);this.events.push('pop')}}
 apply(e:Brick,b:Ball){this.hit(e,b.damage);
 if(b.kind==='frost'||b.kind==='steam')e.slow=3;
 if(b.kind==='ember'||b.kind==='steam')e.burn=3;
 if(b.kind==='spore'||b.kind==='tempest')e.poison=5;
 const near=this.alive.filter(n=>n.id!==e.id&&Math.hypot(n.x-e.x,n.z-e.z)<(b.kind==='meteor'||b.kind==='steam'?2.3:3)).sort((a,c)=>Math.hypot(a.x-e.x,a.z-e.z)-Math.hypot(c.x-e.x,c.z-e.z));
 if(b.kind==='spark'||b.kind==='tempest'){for(const n of near.slice(0,b.kind==='tempest'?3:1)){this.hit(n,b.damage*.55,false);if(b.kind==='tempest')n.poison=5;this.effect(n.x,n.z,ORBS[b.kind].color,.6)}}
 if(b.kind==='meteor'||b.kind==='steam'){for(const n of near){this.hit(n,b.damage*.5,false);if(b.kind==='steam'){n.slow=3;n.burn=3}}this.effect(e.x,e.z,ORBS[b.kind].color,2.3)}
 }
 fire(){if(!this.active||this.fireTime>0)return;this.fireTime=.55/this.rate;for(let hero=0;hero<2;hero++){const x=this.x+(hero===0?-.78:.78),z=this.z-.4,orb=this.orbs[(this.shot+hero)%this.orbs.length];const angle=Math.atan2(Math.min(-1.5,this.aim.z-z),this.aim.x-x),base=10*(1+.35*(orb.rank-1))*this.power*(orb.kind==='stone'?1.6:orb.kind==='meteor'?1.7:1);for(let j=0;j<=this.extra;j++){const a=angle+(j-this.extra/2)*.12;this.balls.push({id:this.serial++,x,z,vx:Math.cos(a)*15,vz:Math.sin(a)*15,kind:orb.kind,damage:base,life:6+orb.rank*.4,last:-1,lock:0,returns:0})}}this.shot++;this.events.push('fire');if(this.balls.length>180)this.balls.splice(0,this.balls.length-180)}
 burst(){if(!this.active)return;if(this.charge<50){this.say('Break enemies to build 50 bond.');return}this.charge-=50;for(const e of this.alive)this.hit(e,25*this.power,false);for(const b of this.balls){b.vz=-Math.abs(b.vz);b.life=Math.max(b.life,3)}this.effect(this.x,this.z,'#e4bbff',6);this.events.push('burst');this.say('Double Trouble! Balls recalled upward.')}
 upgrades(){const out:Upgrade[]=[];for(const [kind,info]of Object.entries(ORBS) as [OrbKind,typeof ORBS[OrbKind]][]){const owned=this.orbs.find(o=>o.kind===kind);if(owned&&owned.rank<5)out.push({id:kind,name:info.name+' '+(owned.rank+1),description:'+35% base damage and more time in the pit.',color:info.color});else if(!owned&&this.orbs.length<4&&!RECIPES.some(r=>r.result===kind))out.push({id:kind,name:'Learn '+info.name,description:info.description,color:info.color})}out.push({id:'power',name:'Sharper little teeth',description:'All balls deal 20% more damage.',color:'#f4c899'});if(this.rate<2.4)out.push({id:'rate',name:'Quick paws',description:'Both chinchillas fire 15% faster.',color:'#cfc0eb'});if(this.extra<2)out.push({id:'extra',name:'More is more',description:'One extra ball per chinchilla in every volley.',color:'#eadfa4'});out.push({id:'heart',name:'Braver together',description:'+20 maximum courage and restore 35 courage.',color:'#e9a6aa'});for(let i=out.length-1;i>0;i--){const j=Math.floor(this.roll()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out.slice(0,3)}
 choose(id:string){if(!this.choice.some(c=>c.id===id))return false;if(id==='power')this.power*=1.2;else if(id==='rate')this.rate*=1.15;else if(id==='extra')this.extra++;else if(id==='heart'){this.maxHp+=20;this.hp=Math.min(this.maxHp,this.hp+35)}else{const owned=this.orbs.find(o=>o.kind===id);if(owned)owned.rank++;else this.orbs.push({kind:id as OrbKind,rank:1})}this.choice=[];this.events.push('upgrade');return true}
 fusionReason(index:number){const r=RECIPES[index];if(!r)return 'Unknown fusion';const a=this.orbs.find(o=>o.kind===r.a),b=this.orbs.find(o=>o.kind===r.b);if(!a||!b)return 'Learn both ingredients';if(a.rank<2||b.rank<2)return 'Raise both ingredients to level 2';if(this.orbs.some(o=>o.kind===r.result))return 'Already fused';return ''}
 fuse(index:number){if(!this.playing||this.lost||this.won||this.choice.length||this.fusionReason(index))return false;const r=RECIPES[index];this.orbs=this.orbs.filter(o=>o.kind!==r.a&&o.kind!==r.b);this.orbs.push({kind:r.result,rank:1});this.events.push('upgrade');this.say(ORBS[r.result].name+' awakened!');return true}
 descend(){if(!this.won)return;this.depth++;this.wave=0;this.enemies=[];this.balls=[];this.effects=[];this.won=false;this.hp=this.maxHp;this.x=0;this.z=7.7;this.spawnWave()}
 step(dt:number,input={x:0,z:0}){if(!this.active)return;dt=Math.min(dt,1/60);this.time+=dt;this.fireTime=Math.max(0,this.fireTime-dt);this.hurt=Math.max(0,this.hurt-dt);this.messageTime=Math.max(0,this.messageTime-dt);this.comboTime-=dt;if(this.comboTime<=0)this.combo=0;const n=Math.max(1,Math.hypot(input.x,input.z));this.x=Math.max(-4.65,Math.min(4.65,this.x+input.x/n*5.5*dt));this.z=Math.max(5.4,Math.min(8.2,this.z+input.z/n*5.5*dt));if(this.auto||this.fireHeld)this.fire();
 this.nextWave-=dt;if(this.wave<12&&(this.nextWave<=0||!this.alive.length))this.spawnWave();
 for(const e of this.alive){e.flash=Math.max(0,e.flash-dt);e.slow=Math.max(0,e.slow-dt);if(e.burn>0){e.burn-=dt;this.hit(e,4*this.power*dt,false)}if(e.poison>0){e.poison-=dt;this.hit(e,3*this.power*dt,false)}if(e.hp<=0)continue;e.z+=dt*(e.boss?.14:.24+.012*this.depth)*(e.slow>0?.4:1);if(e.z>5.0){this.hp-=e.boss?this.hp:12;e.hp=0;this.hurt=.4;this.combo=0;this.events.push('hurt');this.effect(e.x,e.z,'#f28f7f',1.4)}}
 for(const b of this.balls){b.life-=dt;b.lock=Math.max(0,b.lock-dt);const steps=Math.ceil(15*dt/.12);for(let k=0;k<steps&&b.life>0;k++){const px=b.x,pz=b.z;b.x+=b.vx*dt/steps;b.z+=b.vz*dt/steps;if(Math.abs(b.x)>5.75){b.x=Math.sign(b.x)*5.75;b.vx*=-1}if(b.z< -11){b.z=-11;b.vz=Math.abs(b.vz)}if(b.z>9){b.life=0;break}
 if(b.vz>0&&b.returns<3&&[this.x-.78,this.x+.78].some(x=>Math.hypot(b.x-x,b.z-this.z)<.7)){b.vz=-Math.abs(b.vz);b.z=this.z-.72;b.returns++;b.damage*=1.08;this.effect(b.x,b.z,'#f3dcb0',.4)}
 for(const e of this.alive){if(e.id===b.last&&b.lock>0)continue;const w=e.boss?1.5:.64,d=e.boss?.85:.52;if(Math.abs(b.x-e.x)<w+.14&&Math.abs(b.z-e.z)<d+.14){if(px<e.x-w-.1||px>e.x+w+.1){b.vx*=-1;b.x=px}else{b.vz*=-1;b.z=pz}b.last=e.id;b.lock=.12;this.apply(e,b);break}}
 }}this.balls=this.balls.filter(b=>b.life>0);this.effects.forEach(e=>e.age+=dt);this.effects=this.effects.filter(e=>e.age<e.life).slice(-100);
 if(this.hp<=0){this.hp=0;this.lost=true;this.events.push('lose');return}if(this.wave===12&&!this.alive.length){this.won=true;this.events.push('win');return}if(this.xp>=this.xpNext){this.xp-=this.xpNext;this.level++;this.choice=this.upgrades();this.events.push('upgrade')}
 }
}
