import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--enable-unsafe-swiftshader', '--use-gl=angle', '--use-angle=swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1400, height: 980 } });
const errors = [];
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
page.on('console', (m) => { if (m.type() === 'error') errors.push(`console: ${m.text()}`); });
await page.goto('http://localhost:4173/dusty-hollow', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: 'Play as Dora and Enzo' }).click();
await page.waitForSelector('canvas');
await page.waitForTimeout(800);
await page.getByText('Voxel 3D view').click();
await page.waitForTimeout(2500);
await page.locator('canvas').focus();
await page.keyboard.down('ArrowDown');
await page.waitForTimeout(900);
await page.keyboard.up('ArrowDown');
await page.waitForTimeout(1200);
await page.locator('canvas').screenshot({ path: '/tmp/dh-3d.png' });
await page.screenshot({ path: '/tmp/dh-3d-full.png' });
console.log(JSON.stringify({ errors, peek: (await page.locator('.dh-peek').innerText()).split('\n')[0] }));
await browser.close();
process.exit(errors.length ? 1 : 0);
