import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 1000 } });
const errors = [];
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
page.on('console', (m) => { if (m.type() === 'error') errors.push(`console: ${m.text()}`); });
await page.goto('http://localhost:4173/dusty-hollow', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: 'Play as Dora and Enzo' }).click();
await page.waitForSelector('canvas');
await page.waitForTimeout(800);
// Hand ourselves the trowel and some furniture for the yard.
await page.evaluate(() => {
  const k = 'dusty-hollow-save-v1';
  const s = JSON.parse(localStorage.getItem(k));
  s.raisins = 99999;
  s.tools = ['hands', 'net', 'rod', 'shovel', 'can', 'trowel'];
  s.outdoor = [{ id: 'lamp', x: 6, y: 13 }, { id: 'cactus', x: 8, y: 13 }, { id: 'table', x: 7, y: 14 }];
  s.edits = {};
  for (let x = 5; x <= 9; x++) for (let y = 12; y <= 15; y++) if (!(x === 6 && y === 13) && !(x === 8 && y === 13) && !(x === 7 && y === 14)) s.edits[`${x},${y}`] = 'path';
  localStorage.setItem(k, JSON.stringify(s));
});
await page.reload({ waitUntil: 'networkidle' });
await page.getByRole('button', { name: 'Continue' }).click();
await page.waitForSelector('canvas');
await page.locator('canvas').focus();
await page.waitForTimeout(700);
await page.keyboard.down('ArrowDown');
await page.waitForTimeout(900);
await page.keyboard.up('ArrowDown');
await page.waitForTimeout(1200);
await page.mouse.move(5, 5);
const tools = await page.locator('.dh-tools button').count();
await page.keyboard.press('Digit6');
await page.waitForTimeout(400);
const peek = await page.locator('.dh-peek').innerText();
await page.locator('canvas').screenshot({ path: '/tmp/land.png' });
console.log(JSON.stringify({ errors, tools, peek: peek.split('\n') }, null, 1));
await browser.close();
process.exit(errors.length ? 1 : 0);
