import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 980 } });
const errors = [];
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
page.on('console', (m) => { if (m.type() === 'error') errors.push(`console: ${m.text()}`); });
await page.goto('http://localhost:4173/dusty-hollow', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: 'Play as Dora and Enzo' }).click();
await page.waitForSelector('canvas');
await page.locator('canvas').focus();
await page.waitForTimeout(1000);
await page.keyboard.down('ArrowRight');
await page.waitForTimeout(1200);
await page.keyboard.up('ArrowRight');
await page.waitForTimeout(1400);
await page.locator('canvas').screenshot({ path: '/tmp/story-1.png' });
// Walk south toward the sea for water, sand and the shoreline.
await page.keyboard.down('ArrowDown');
await page.waitForTimeout(2600);
await page.keyboard.up('ArrowDown');
await page.waitForTimeout(1400);
await page.locator('canvas').screenshot({ path: '/tmp/story-2.png' });
console.log(JSON.stringify({ errors, peek: (await page.locator('.dh-peek').innerText()).split('\n')[0] }));
await browser.close();
process.exit(errors.length ? 1 : 0);
