import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--enable-unsafe-swiftshader', '--use-gl=angle', '--use-angle=swiftshader'] });
const page = await browser.newContext().then((c) => c.newPage());
const errors = [];
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
await page.goto('https://chinchillas.jason.engineering/dusty-hollow', { waitUntil: 'networkidle' });
const buttons = await page.locator('.dh-choose button').allInnerTexts();
await page.getByRole('button', { name: 'Play as Dora and Enzo' }).click();
await page.waitForSelector('canvas');
await page.waitForTimeout(1200);
const hud = await page.locator('.dh-hud').innerText();
const hasVoxel = await page.getByText('Voxel 3D view').count();
await page.locator('canvas').screenshot({ path: '/tmp/live-2d.png' });
await page.getByText('Voxel 3D view').click();
await page.waitForTimeout(2200);
const is3d = await page.locator('.dh-stage3d').count();
await page.locator('canvas').screenshot({ path: '/tmp/live-3d.png' });
console.log(JSON.stringify({ errors, buttons, hud: hud.split('\n'), hasVoxel, is3d }, null, 1));
await browser.close();
