import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 1000 } });
const errors = [];
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
page.on('console', (m) => { if (m.type() === 'error') errors.push(`console: ${m.text()}`); });
const open = async () => {
  await page.locator('canvas').first().focus();
  await page.keyboard.down('ArrowUp'); await page.waitForTimeout(750); await page.keyboard.up('ArrowUp');
  await page.waitForTimeout(250);
  await page.keyboard.press('Space');
  await page.waitForTimeout(700);
};
await page.goto('http://localhost:4173/dusty-hollow', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: 'Play as Dora and Enzo' }).click();
await page.waitForSelector('canvas');
await page.waitForTimeout(900);
await open();
const bare = await page.locator('.dh-caption').innerText();
await page.mouse.move(5, 5);
  await page.waitForTimeout(200);
  await page.locator('.dh-room').screenshot({ path: '/tmp/tent-bare.png' });
await page.keyboard.press('Escape');
await page.waitForTimeout(300);
// Two pieces in the tent: the smallest room the game has.
await page.evaluate(() => {
  const k = 'dusty-hollow-save-v1';
  const s = JSON.parse(localStorage.getItem(k));
  s.furniture = [{ id: 'bed', x: 0, y: 0 }, { id: 'lamp', x: 2, y: 1 }];
  localStorage.setItem(k, JSON.stringify(s));
});
await page.reload({ waitUntil: 'networkidle' });
await page.getByRole('button', { name: 'Continue' }).click();
await page.waitForSelector('canvas');
await page.waitForTimeout(800);
await open();
const furnished = await page.locator('.dh-caption').innerText();
await page.mouse.move(5, 5);
  await page.waitForTimeout(200);
  await page.locator('.dh-room').screenshot({ path: '/tmp/tent-two.png' });
console.log(JSON.stringify({ errors, bare, furnished }, null, 1));
await browser.close();
process.exit(errors.length ? 1 : 0);
