/* oxlint-disable react/react-compiler -- The deterministic engine is intentionally mutable and read on each animation-driven render. */
/* oxlint-disable next/no-html-link-for-pages -- Match the arcade's hard navigation so leaving always tears down the game loop. */
'use client';
import {useEffect,useRef,useState} from 'react';
import {SoccerGame,MATCH_SECONDS,RIVALS,CUP_ROUNDS,type Mode} from '../../lib/soccer-game';
import {drawSoccer,toPitch,W,H} from '../../lib/soccer-scene';
type Record_={cups:number;best:number};
const SAVE='fluffball-cup-v1';
const readRecord=():Record_=>{try{const r=JSON.parse(localStorage.getItem(SAVE)??'');return {cups:Number(r.cups)||0,best:Number(r.best)||0}}catch{return {cups:0,best:0}}};
const rivalName=(g:SoccerGame)=>g.rival.id==='ember'?'Enzo’s Ember FC':g.rival.name;
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),game=useRef(new SoccerGame()),keys=useRef(new Set<string>()),[tick,setTick]=useState(0),[error,setError]=useState(false),[record,setRecord]=useState<Record_>({cups:0,best:0}),saved=useRef<SoccerGame|null>(null);const g=game.current;
 useEffect(()=>setRecord(readRecord()),[]);
 function begin(mode:Mode,round=0){game.current=new SoccerGame({mode,round});game.current.start();saved.current=null;keys.current.clear();canvas.current?.focus();setTick(t=>t+1)}
 function pause(){game.current.pause();keys.current.clear();canvas.current?.focus();setTick(t=>t+1)}
 function action(which:'pass'|'shoot'|'switch'|'chip'){if(which==='pass')game.current.pass();else if(which==='shoot')game.current.shoot();else if(which==='chip')game.current.chip();else game.current.switchPlayer();canvas.current?.focus();setTick(t=>t+1)}
 // Record how far the cup run got, once per finished match.
 if(g.state==='finished'&&g.mode==='cup'&&saved.current!==g){saved.current=g;const won=g.winner===0,reached=g.round+(won?1:0),next={cups:record.cups+(won&&g.round===2?1:0),best:Math.max(record.best,reached)};if(next.cups!==record.cups||next.best!==record.best){setRecord(next);try{localStorage.setItem(SAVE,JSON.stringify(next))}catch{/* private mode: the run still plays, it just isn't remembered */}}}
 useEffect(()=>{const c=canvas.current?.getContext('2d');if(!c){setError(true);return}let raf=0,last=0,acc=0,ui=0;const loop=(now:number)=>{acc+=last?Math.min(.1,(now-last)/1000):0;last=now;while(acc>=1/120){game.current.step(1/120,{x:+(keys.current.has('d')||keys.current.has('arrowright'))-+(keys.current.has('a')||keys.current.has('arrowleft')),y:+(keys.current.has('s')||keys.current.has('arrowdown'))-+(keys.current.has('w')||keys.current.has('arrowup')),sprint:keys.current.has('shift')});acc-=1/120}game.current.events.splice(0);drawSoccer(c,game.current,now/1000);if(now-ui>60){setTick(t=>t+1);ui=now}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('button,a,input'))return;const k=e.key.toLowerCase();if([' ','tab','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.current.add(k);if(e.repeat)return;if(k==='j')action('pass');if(k==='k'||k===' ')action('shoot');if(k==='l')action('chip');if(k==='tab')action('switch');if(k==='p'||k==='escape')pause()};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>{keys.current.clear();if(game.current.state==='playing')game.current.pause()};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{cancelAnimationFrame(raf);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur)}},[]);
 const hold=(key:string,label:string)=><button onPointerDown={e=>{e.preventDefault();keys.current.add(key);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={()=>keys.current.delete(key)} onPointerCancel={()=>keys.current.delete(key)} onLostPointerCapture={()=>keys.current.delete(key)}>{label}</button>;
 const total=g.possession[0]+g.possession[1],share=total?Math.round(g.possession[0]/total*100):50;
 const bracket=<ol className="soccer-bracket">{RIVALS.map((r,i)=><li key={r.id} className={g.mode==='cup'&&i<g.round?'won':g.mode==='cup'&&i===g.round?'now':''}><small>{CUP_ROUNDS[i]}</small>{r.id==='ember'?'Enzo’s Ember FC':r.name}</li>)}</ol>;
 let overlay:React.ReactNode=null;
 if(error)overlay=<><span className="soccer-eyebrow">CANVAS UNAVAILABLE</span><h2>Try another browser.</h2></>;
 else if(g.state==='ready')overlay=<><span className="soccer-eyebrow">THE FLUFFBALL CUP</span><h2>{'Best friends.\nOpposite sides.'}</h2><p>Lead Dora’s blue Sky Squad through three knockout rounds to the final against Enzo, or warm up with a friendly.</p>{bracket}<div className="soccer-choices"><button className="soccer-primary" onClick={()=>begin('cup')}>Play the cup →</button><button className="soccer-secondary" onClick={()=>begin('friendly')}>Friendly vs Enzo</button></div><small>{record.cups?`Cups won: ${record.cups} · `:record.best?`Best run: reached the ${CUP_ROUNDS[Math.min(2,record.best)].toLowerCase()} · `:''}WASD move · J pass · K shoot · L Cloud Chip · Mouse aim</small></>;
 else if(g.state==='paused')overlay=<><span className="soccer-eyebrow">TIME OUT</span><h2>A quick breather.</h2><p>The match clock is stopped.</p><button className="soccer-primary" onClick={pause}>Back to the match →</button></>;
 else if(g.state==='finished'){
  const stats=<p className="soccer-stats">Shots {g.shots[0]} – {g.shots[1]} · Possession {share}% – {100-share}%</p>;
  if(g.mode==='friendly')overlay=<><span className="soccer-eyebrow">FULL TIME · FRIENDLY</span><h2>{g.winner===0?'Dora wins the friendly!':g.winner===1?'Enzo wins the friendly!':'Honours even.'}</h2><p>{g.score[0]} – {g.score[1]} · {g.winner===null?'A friendly draw. Rematch?':'Time for a victory dust bath.'}</p>{stats}<div className="soccer-choices"><button className="soccer-primary" onClick={()=>begin('friendly')}>Play a rematch →</button><button className="soccer-secondary" onClick={()=>begin('cup')}>Play the cup</button></div></>;
  else if(g.winner===0&&g.round===2)overlay=<><span className="soccer-eyebrow">CUP WINNERS</span><h2>{'The Fluffball Cup\nis Dora’s!'}</h2><p>{g.score[0]} – {g.score[1]} in the final{g.golden?' on a golden goal':''}. Enzo shakes paws and demands a rematch.</p>{stats}<button className="soccer-primary" onClick={()=>begin('cup')}>Defend the cup →</button></>;
  else if(g.winner===0)overlay=<><span className="soccer-eyebrow">{CUP_ROUNDS[g.round].toUpperCase()} · THROUGH</span><h2>{`Into the ${CUP_ROUNDS[g.round+1].toLowerCase()}!`}</h2><p>{g.score[0]} – {g.score[1]} against {rivalName(g)}{g.golden?' on a golden goal':''}. Next up: {RIVALS[g.round+1].id==='ember'?'Enzo’s Ember FC':RIVALS[g.round+1].name}.</p>{stats}<button className="soccer-primary" onClick={()=>begin('cup',g.round+1)}>{`Play the ${CUP_ROUNDS[g.round+1].toLowerCase()} →`}</button></>;
  else overlay=<><span className="soccer-eyebrow">{CUP_ROUNDS[g.round].toUpperCase()} · KNOCKED OUT</span><h2>{g.round===2?'Enzo lifts the cup.':`${g.rival.name} go through.`}</h2><p>{g.score[0]} – {g.score[1]}{g.golden?' on a golden goal':''}. Dust off and go again.</p>{stats}<div className="soccer-choices"><button className="soccer-primary" onClick={()=>begin('cup',g.round)}>{`Replay the ${CUP_ROUNDS[g.round].toLowerCase()} →`}</button><button className="soccer-secondary" onClick={()=>begin('cup')}>Start the cup again</button></div></>;
 }
 const clock=g.golden?'GOLDEN GOAL':`${Math.floor(g.time/60)}:${String(Math.floor(g.time%60)).padStart(2,'0')}`;
 void tick;return <main className="soccer-shell"><header className="soccer-header"><a href="/">← MAIN ARCADE <span>FLUFFBALL CUP</span></a><button disabled={!['playing','paused'].includes(g.state)} onClick={pause}>{g.state==='paused'?'Resume':'Pause'} · P</button></header><div className="soccer-title"><div><span className="soccer-eyebrow">FRIENDLY RIVALS · FOUR-A-SIDE</span><h1>Small paws. Big match.</h1></div><p>Three knockout rounds to the Fluffball Cup,<br/>with Enzo’s Ember FC waiting in the final.</p></div><section className="soccer-board" aria-label="Fluffball soccer match"><div className="soccer-score"><div className="soccer-team blue"><span>D</span><b>DORA<small>SKY SQUAD · YOU →</small></b></div><strong>{g.score[0]} <i>–</i> {g.score[1]}</strong><div className={`soccer-team rival-${g.rival.id}`}><b>{g.rival.captain.toUpperCase()}<small>← {g.rival.name.toUpperCase()} · CPU</small></b><span>{g.rival.captain[0]}</span></div><time>{clock} {!g.golden&&<small>/ {MATCH_SECONDS/60|0}:{String(MATCH_SECONDS%60).padStart(2,'0')}</small>}</time></div>
 <div className="soccer-pitch"><canvas ref={canvas} width={W} height={H} tabIndex={0} aria-label="Soccer field. WASD to move, mouse to aim, J pass, K shoot, L Cloud Chip, Tab switch, Shift sprint." onPointerDown={()=>canvas.current?.focus()} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect(),p=toPitch((e.clientX-r.left)/r.width*W,(e.clientY-r.top)/r.height*H);g.aim={x:Math.max(0,Math.min(100,p.x)),y:Math.max(1,Math.min(59,p.y))}}}/>
 {g.state==='goal'&&<div className="soccer-goal"><span>{g.golden?'GOLDEN GOAL!':'GOOOAL!'}</span><b>{g.message}</b></div>}
 {overlay&&<div className="soccer-overlay"><div>{overlay}</div></div>}
 </div><div className="soccer-status"><span>{g.mode==='cup'?CUP_ROUNDS[g.round].toUpperCase():'FRIENDLY'} <b>vs {rivalName(g)}</b></span><span>SELECTED <b>{g.players[g.active].name}</b></span><div className="soccer-stamina"><span>STAMINA</span><i><em style={{width:g.players[g.active].stamina*100+'%'}}/></i></div><div className={`soccer-stamina soccer-meter${g.meter>=1?' full':''}`}><span>{g.meter>=1?'CLOUD CHIP READY · L':'FLUFF METER'}</span><i><em style={{width:g.meter*100+'%'}}/></i></div><span>{g.owner===null?'LOOSE BALL':g.players[g.owner].team===0?'SKY SQUAD POSSESSION':`${g.rival.name.toUpperCase()} POSSESSION`}</span><b>{g.messageTime>0&&g.state==='playing'?g.message:''}</b></div></section>
 <div className="soccer-actions"><div>{hold('a','←')}{hold('w','↑')}{hold('s','↓')}{hold('d','→')}{hold('shift','SPRINT')}</div><div><button onClick={()=>action('pass')}>J · PASS</button><button onClick={()=>action('shoot')}>K · SHOOT</button><button disabled={g.meter<1} onClick={()=>action('chip')}>L · CHIP</button><button onClick={()=>action('switch')}>TAB · SWITCH</button></div></div><div className="soccer-help"><p><b>Build the play.</b> Move with WASD or arrows. Hold Shift to sprint. Tap J to pass; control follows a teammate receiving the ball. Passes that arrive and tackles you win fill the Fluff meter.</p><p><b>Find the corner.</b> Point your mouse to aim, then press K or Space to shoot. Keepers dive, so get close and go for the far corner. With a full meter, L lofts a Cloud Chip over everyone’s heads.</p><p><b>Win the cup.</b> Beat Viscacha United, then Degu Dynamo, then Enzo’s Ember FC, whose captain bursts forward with an Ember Dash. A level cup match goes to golden goal.</p></div></main>
}
